## PHASE 0 – Load & hiểu data

In [2]:
# Visualization
import matplotlib.pyplot as plt

# Data processing
import pandas as pd

# Machine Learning
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import roc_auc_score

# CatBoost
from catboost import CatBoostClassifier, Pool, cv

In [3]:
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

Số dòng, số cột

In [4]:
print("số dòng:", len(df))
print("số cột:", len(df.columns))

số dòng: 1470
số cột: 35


In [5]:
df['Attrition'].value_counts(normalize=True)

Attrition
No     0.838776
Yes    0.161224
Name: proportion, dtype: float64

**Nhận thấy: Dữ liệu bị mất cân bằng**

Kiểm tra missing value

In [6]:
df.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSince

## PHASE 1 – Xác định feature types

Drop các feature vô nghĩa

In [7]:
drop_cols = [
    'EmployeeNumber',   # ID
    'EmployeeCount',    # constant
    'Over18',           # constant
    'StandardHours'     # constant
]
df = df.drop(columns=drop_cols)

In [8]:
df['Attrition'] = df['Attrition'].map({'No': 0, 'Yes': 1})

In [9]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

In [10]:
df.head().T

,0,1,2,3,4
Age,41,49,37,33,27
Attrition,1,0,1,0,0
BusinessTravel,Travel_Rarely,Travel_Frequently,Travel_Rarely,Travel_Frequently,Travel_Rarely
DailyRate,1102,279,1373,1392,591
Department,Sales,Research & Development,Research & Development,Research & Development,Research & Development
DistanceFromHome,1,8,2,3,2
Education,2,1,2,4,1
EducationField,Life Sciences,Life Sciences,Other,Life Sciences,Medical
EnvironmentSatisfaction,2,3,4,4,1
Gender,Female,Male,Male,Female,Male


In [11]:
cat_features = [
    'BusinessTravel',
    'Department',
    'EducationField',
    'Gender',
    'JobRole',
    'MaritalStatus',
    'OverTime'
]

## PHASE 2 – Split dữ liệu
Chia 80/20

In [12]:
X = df.drop(columns='Attrition')
y = df['Attrition']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)
print("Số lượng mẫu training:", len(y_train))
print("Số lượng mẫu testing:", len(y_test))

Số lượng mẫu training: 1176
Số lượng mẫu testing: 294


## PHASE 3 – Pool cho CatBoost

In [13]:
train_pool = Pool(
    X_train, y_train,
    cat_features=cat_features
)

test_pool = Pool(
    X_test, y_test,
    cat_features=cat_features
)

## PHASE 4 – Train baseline CatBoost (KHÔNG TUNING)

In [14]:
baseline_model = CatBoostClassifier(
    loss_function='Logloss',
    iterations=100,
    auto_class_weights='Balanced',
    random_seed=42,
    verbose=False
)

baseline_model.fit(
    train_pool,
    plot=True
)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

In [15]:
proba_test = baseline_model.predict_proba(X_test)[:,1]
auc_test = roc_auc_score(y_test, proba_test)

train_pred = baseline_model.predict_proba(X_train)[:,1]
auc_train = roc_auc_score(y_train, train_pred)

gap = auc_train - auc_test

print(f"Train AUC: {auc_train:.4f}")
print(f"Test AUC:  {auc_test:.4f}")
print(f"Gap:       {gap:.4f}")

Train AUC: 0.9979
Test AUC:  0.7890
Gap:       0.2089


## Phrase 5 - Cross - Validation

In [16]:
cv_params = {
    'iterations': 1000,
    'loss_function': 'Logloss',
    'eval_metric': 'AUC',
    'random_seed': 42,
    'early_stopping_rounds': 50,
}

cv_results = cv(
    pool=train_pool,
    params=cv_params,
    fold_count=5,
    shuffle=True,
    partition_random_seed=42,
    plot=True,
    verbose=False,
)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

Training on fold [0/5]

bestTest = 0.812466773
bestIteration = 23

Training on fold [1/5]

bestTest = 0.8123163238
bestIteration = 116

Training on fold [2/5]

bestTest = 0.7686347849
bestIteration = 37

Training on fold [3/5]

bestTest = 0.8157894737
bestIteration = 151

Training on fold [4/5]

bestTest = 0.8589366818
bestIteration = 101



In [17]:
best_iter = cv_results['test-AUC-mean'].idxmax()
best_auc = cv_results['test-AUC-mean'].max()

print(f"Best iteration: {best_iter}")
print(f"Best CV AUC: {best_auc:.4f}")

Best iteration: 150
Best CV AUC: 0.8086


## Phrase 6 - Grid Search

In [34]:
base_model = CatBoostClassifier(
    iterations = best_iter + 30,
    loss_function='Logloss',
    auto_class_weights='Balanced',
    eval_metric='AUC',
    random_seed=42,
    task_type='GPU',
    verbose=20,
)

#### Tuning 

##### Lần 1

In [39]:
param_grid = {
    "depth": [2, 3, 5],
    "learning_rate": [0.03, 0.05, 0.1],
    "l2_leaf_reg": [20, 30, 40]
}

gs = GridSearchCV(
    estimator=base_model,
    param_grid=param_grid,
    cv=5,
    scoring="roc_auc",
    return_train_score=True,
)

gs.fit(X_train, y_train, cat_features=cat_features)

results = pd.DataFrame(gs.cv_results_)

Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.5ms	remaining: 3.13s
20:	total: 339ms	remaining: 2.56s
40:	total: 645ms	remaining: 2.19s
60:	total: 954ms	remaining: 1.86s
80:	total: 1.26s	remaining: 1.54s
100:	total: 1.57s	remaining: 1.23s
120:	total: 1.87s	remaining: 914ms
140:	total: 2.19s	remaining: 607ms
160:	total: 2.51s	remaining: 296ms
179:	total: 2.8s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.8ms	remaining: 3.19s
20:	total: 319ms	remaining: 2.41s
40:	total: 643ms	remaining: 2.18s
60:	total: 960ms	remaining: 1.87s
80:	total: 1.27s	remaining: 1.55s
100:	total: 1.56s	remaining: 1.22s
120:	total: 1.89s	remaining: 921ms
140:	total: 2.2s	remaining: 609ms
160:	total: 2.5s	remaining: 296ms
179:	total: 2.81s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.4ms	remaining: 3.12s
20:	total: 310ms	remaining: 2.35s
40:	total: 616ms	remaining: 2.09s
60:	total: 926ms	remaining: 1.8s
80:	total: 1.23s	remaining: 1.51s
100:	total: 1.55s	remaining: 1.22s
120:	total: 1.86s	remaining: 908ms
140:	total: 2.18s	remaining: 602ms
160:	total: 2.51s	remaining: 296ms
179:	total: 2.81s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20ms	remaining: 3.58s
20:	total: 348ms	remaining: 2.63s
40:	total: 650ms	remaining: 2.2s
60:	total: 962ms	remaining: 1.88s
80:	total: 1.28s	remaining: 1.56s
100:	total: 1.58s	remaining: 1.24s
120:	total: 1.89s	remaining: 924ms
140:	total: 2.22s	remaining: 615ms
160:	total: 2.56s	remaining: 302ms
179:	total: 2.88s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.8ms	remaining: 3.01s
20:	total: 334ms	remaining: 2.53s
40:	total: 653ms	remaining: 2.21s
60:	total: 978ms	remaining: 1.91s
80:	total: 1.28s	remaining: 1.56s
100:	total: 1.58s	remaining: 1.24s
120:	total: 1.9s	remaining: 928ms
140:	total: 2.22s	remaining: 614ms
160:	total: 2.54s	remaining: 300ms
179:	total: 2.83s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 24.3ms	remaining: 4.35s
20:	total: 341ms	remaining: 2.58s
40:	total: 691ms	remaining: 2.34s
60:	total: 1s	remaining: 1.96s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.62s	remaining: 1.27s
120:	total: 2.01s	remaining: 980ms
140:	total: 2.44s	remaining: 676ms
160:	total: 2.85s	remaining: 336ms
179:	total: 3.19s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.8ms	remaining: 3.71s
20:	total: 405ms	remaining: 3.07s
40:	total: 795ms	remaining: 2.69s
60:	total: 1.11s	remaining: 2.16s
80:	total: 1.46s	remaining: 1.79s
100:	total: 1.78s	remaining: 1.39s
120:	total: 2.14s	remaining: 1.04s
140:	total: 2.47s	remaining: 682ms
160:	total: 2.83s	remaining: 334ms
179:	total: 3.13s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.5ms	remaining: 3.13s
20:	total: 331ms	remaining: 2.5s
40:	total: 653ms	remaining: 2.21s
60:	total: 958ms	remaining: 1.87s
80:	total: 1.29s	remaining: 1.58s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.94s	remaining: 945ms
140:	total: 2.28s	remaining: 632ms
160:	total: 2.62s	remaining: 309ms
179:	total: 2.92s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19ms	remaining: 3.4s
20:	total: 340ms	remaining: 2.57s
40:	total: 649ms	remaining: 2.2s
60:	total: 972ms	remaining: 1.9s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.66s	remaining: 1.3s
120:	total: 2.01s	remaining: 979ms
140:	total: 2.34s	remaining: 648ms
160:	total: 2.67s	remaining: 316ms
179:	total: 3.01s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.8ms	remaining: 3s
20:	total: 346ms	remaining: 2.62s
40:	total: 664ms	remaining: 2.25s
60:	total: 980ms	remaining: 1.91s
80:	total: 1.3s	remaining: 1.59s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.92s	remaining: 938ms
140:	total: 2.24s	remaining: 621ms
160:	total: 2.56s	remaining: 303ms
179:	total: 2.87s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.1ms	remaining: 3.07s
20:	total: 334ms	remaining: 2.53s
40:	total: 665ms	remaining: 2.25s
60:	total: 972ms	remaining: 1.9s
80:	total: 1.27s	remaining: 1.56s
100:	total: 1.59s	remaining: 1.25s
120:	total: 1.93s	remaining: 941ms
140:	total: 2.24s	remaining: 620ms
160:	total: 2.61s	remaining: 308ms
179:	total: 2.97s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.5ms	remaining: 3.5s
20:	total: 350ms	remaining: 2.65s
40:	total: 689ms	remaining: 2.33s
60:	total: 1.03s	remaining: 2.02s
80:	total: 1.38s	remaining: 1.68s
100:	total: 1.72s	remaining: 1.34s
120:	total: 2.04s	remaining: 996ms
140:	total: 2.36s	remaining: 653ms
160:	total: 2.68s	remaining: 317ms
179:	total: 2.98s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.6ms	remaining: 3.69s
20:	total: 337ms	remaining: 2.55s
40:	total: 653ms	remaining: 2.21s
60:	total: 967ms	remaining: 1.89s
80:	total: 1.27s	remaining: 1.55s
100:	total: 1.58s	remaining: 1.24s
120:	total: 1.91s	remaining: 929ms
140:	total: 2.22s	remaining: 614ms
160:	total: 2.54s	remaining: 300ms
179:	total: 2.84s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.5ms	remaining: 3.32s
20:	total: 353ms	remaining: 2.67s
40:	total: 694ms	remaining: 2.35s
60:	total: 1.03s	remaining: 2s
80:	total: 1.38s	remaining: 1.69s
100:	total: 1.73s	remaining: 1.35s
120:	total: 2.05s	remaining: 999ms
140:	total: 2.37s	remaining: 656ms
160:	total: 2.73s	remaining: 322ms
179:	total: 3.06s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.6ms	remaining: 3.33s
20:	total: 329ms	remaining: 2.49s
40:	total: 642ms	remaining: 2.17s
60:	total: 975ms	remaining: 1.9s
80:	total: 1.29s	remaining: 1.58s
100:	total: 1.6s	remaining: 1.25s
120:	total: 1.9s	remaining: 927ms
140:	total: 2.24s	remaining: 618ms
160:	total: 2.55s	remaining: 301ms
179:	total: 2.86s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.3ms	remaining: 3.09s
20:	total: 328ms	remaining: 2.48s
40:	total: 643ms	remaining: 2.18s
60:	total: 955ms	remaining: 1.86s
80:	total: 1.26s	remaining: 1.54s
100:	total: 1.6s	remaining: 1.25s
120:	total: 1.93s	remaining: 942ms
140:	total: 2.27s	remaining: 629ms
160:	total: 2.6s	remaining: 307ms
179:	total: 2.9s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.8ms	remaining: 3.18s
20:	total: 334ms	remaining: 2.53s
40:	total: 643ms	remaining: 2.18s
60:	total: 958ms	remaining: 1.87s
80:	total: 1.29s	remaining: 1.58s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.93s	remaining: 939ms
140:	total: 2.25s	remaining: 623ms
160:	total: 2.58s	remaining: 305ms
179:	total: 2.89s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.7ms	remaining: 2.99s
20:	total: 340ms	remaining: 2.57s
40:	total: 654ms	remaining: 2.22s
60:	total: 958ms	remaining: 1.87s
80:	total: 1.26s	remaining: 1.54s
100:	total: 1.56s	remaining: 1.22s
120:	total: 1.87s	remaining: 914ms
140:	total: 2.18s	remaining: 604ms
160:	total: 2.5s	remaining: 295ms
179:	total: 2.81s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.9ms	remaining: 3.56s
20:	total: 368ms	remaining: 2.78s
40:	total: 707ms	remaining: 2.4s
60:	total: 1.04s	remaining: 2.03s
80:	total: 1.36s	remaining: 1.66s
100:	total: 1.67s	remaining: 1.31s
120:	total: 2s	remaining: 978ms
140:	total: 2.32s	remaining: 642ms
160:	total: 2.65s	remaining: 313ms
179:	total: 2.94s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20ms	remaining: 3.58s
20:	total: 341ms	remaining: 2.58s
40:	total: 639ms	remaining: 2.17s
60:	total: 1.01s	remaining: 1.97s
80:	total: 1.39s	remaining: 1.7s
100:	total: 1.72s	remaining: 1.35s
120:	total: 2.1s	remaining: 1.02s
140:	total: 2.43s	remaining: 673ms
160:	total: 2.75s	remaining: 325ms
179:	total: 3.08s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.4ms	remaining: 2.93s
20:	total: 333ms	remaining: 2.52s
40:	total: 656ms	remaining: 2.22s
60:	total: 978ms	remaining: 1.91s
80:	total: 1.28s	remaining: 1.57s
100:	total: 1.6s	remaining: 1.25s
120:	total: 1.94s	remaining: 948ms
140:	total: 2.26s	remaining: 624ms
160:	total: 2.58s	remaining: 305ms
179:	total: 2.91s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.8ms	remaining: 3.54s
20:	total: 374ms	remaining: 2.83s
40:	total: 695ms	remaining: 2.36s
60:	total: 1s	remaining: 1.96s
80:	total: 1.33s	remaining: 1.63s
100:	total: 1.65s	remaining: 1.29s
120:	total: 1.96s	remaining: 955ms
140:	total: 2.28s	remaining: 630ms
160:	total: 2.58s	remaining: 305ms
179:	total: 2.89s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.6ms	remaining: 2.97s
20:	total: 325ms	remaining: 2.46s
40:	total: 636ms	remaining: 2.15s
60:	total: 962ms	remaining: 1.88s
80:	total: 1.27s	remaining: 1.55s
100:	total: 1.58s	remaining: 1.24s
120:	total: 1.89s	remaining: 923ms
140:	total: 2.21s	remaining: 610ms
160:	total: 2.55s	remaining: 301ms
179:	total: 2.85s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.9ms	remaining: 3.39s
20:	total: 357ms	remaining: 2.7s
40:	total: 667ms	remaining: 2.26s
60:	total: 978ms	remaining: 1.91s
80:	total: 1.28s	remaining: 1.57s
100:	total: 1.63s	remaining: 1.27s
120:	total: 1.94s	remaining: 945ms
140:	total: 2.23s	remaining: 618ms
160:	total: 2.55s	remaining: 301ms
179:	total: 2.85s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.1ms	remaining: 3.06s
20:	total: 348ms	remaining: 2.64s
40:	total: 662ms	remaining: 2.24s
60:	total: 979ms	remaining: 1.91s
80:	total: 1.29s	remaining: 1.58s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.95s	remaining: 953ms
140:	total: 2.33s	remaining: 644ms
160:	total: 2.69s	remaining: 318ms
179:	total: 3.03s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.8ms	remaining: 3.18s
20:	total: 376ms	remaining: 2.85s
40:	total: 765ms	remaining: 2.59s
60:	total: 1.15s	remaining: 2.24s
80:	total: 1.5s	remaining: 1.83s
100:	total: 1.83s	remaining: 1.43s
120:	total: 2.18s	remaining: 1.06s
140:	total: 2.52s	remaining: 698ms
160:	total: 2.86s	remaining: 337ms
179:	total: 3.19s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.5ms	remaining: 3.13s
20:	total: 325ms	remaining: 2.46s
40:	total: 616ms	remaining: 2.09s
60:	total: 929ms	remaining: 1.81s
80:	total: 1.23s	remaining: 1.51s
100:	total: 1.53s	remaining: 1.19s
120:	total: 1.82s	remaining: 889ms
140:	total: 2.14s	remaining: 592ms
160:	total: 2.44s	remaining: 288ms
179:	total: 2.72s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.4ms	remaining: 3.11s
20:	total: 313ms	remaining: 2.37s
40:	total: 620ms	remaining: 2.1s
60:	total: 929ms	remaining: 1.81s
80:	total: 1.23s	remaining: 1.5s
100:	total: 1.54s	remaining: 1.2s
120:	total: 1.86s	remaining: 907ms
140:	total: 2.17s	remaining: 600ms
160:	total: 2.48s	remaining: 292ms
179:	total: 2.79s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.9ms	remaining: 3.02s
20:	total: 313ms	remaining: 2.37s
40:	total: 616ms	remaining: 2.09s
60:	total: 932ms	remaining: 1.82s
80:	total: 1.24s	remaining: 1.52s
100:	total: 1.55s	remaining: 1.21s
120:	total: 1.86s	remaining: 905ms
140:	total: 2.16s	remaining: 597ms
160:	total: 2.47s	remaining: 292ms
179:	total: 2.78s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.1ms	remaining: 3.42s
20:	total: 333ms	remaining: 2.52s
40:	total: 646ms	remaining: 2.19s
60:	total: 946ms	remaining: 1.84s
80:	total: 1.24s	remaining: 1.52s
100:	total: 1.56s	remaining: 1.22s
120:	total: 1.87s	remaining: 911ms
140:	total: 2.17s	remaining: 601ms
160:	total: 2.49s	remaining: 294ms
179:	total: 2.78s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.4ms	remaining: 3.48s
20:	total: 337ms	remaining: 2.55s
40:	total: 665ms	remaining: 2.25s
60:	total: 982ms	remaining: 1.91s
80:	total: 1.3s	remaining: 1.59s
100:	total: 1.62s	remaining: 1.27s
120:	total: 1.96s	remaining: 955ms
140:	total: 2.31s	remaining: 638ms
160:	total: 2.63s	remaining: 310ms
179:	total: 2.93s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.3ms	remaining: 3.1s
20:	total: 339ms	remaining: 2.57s
40:	total: 656ms	remaining: 2.22s
60:	total: 995ms	remaining: 1.94s
80:	total: 1.29s	remaining: 1.58s
100:	total: 1.59s	remaining: 1.25s
120:	total: 1.92s	remaining: 935ms
140:	total: 2.22s	remaining: 614ms
160:	total: 2.52s	remaining: 298ms
179:	total: 2.82s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.5ms	remaining: 2.95s
20:	total: 316ms	remaining: 2.39s
40:	total: 638ms	remaining: 2.16s
60:	total: 940ms	remaining: 1.83s
80:	total: 1.27s	remaining: 1.55s
100:	total: 1.56s	remaining: 1.22s
120:	total: 1.87s	remaining: 911ms
140:	total: 2.18s	remaining: 603ms
160:	total: 2.49s	remaining: 294ms
179:	total: 2.79s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.7ms	remaining: 3.17s
20:	total: 345ms	remaining: 2.61s
40:	total: 658ms	remaining: 2.23s
60:	total: 972ms	remaining: 1.9s
80:	total: 1.27s	remaining: 1.55s
100:	total: 1.58s	remaining: 1.24s
120:	total: 1.9s	remaining: 928ms
140:	total: 2.22s	remaining: 615ms
160:	total: 2.54s	remaining: 300ms
179:	total: 2.85s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.4ms	remaining: 2.94s
20:	total: 323ms	remaining: 2.44s
40:	total: 640ms	remaining: 2.17s
60:	total: 970ms	remaining: 1.89s
80:	total: 1.28s	remaining: 1.56s
100:	total: 1.59s	remaining: 1.24s
120:	total: 1.91s	remaining: 931ms
140:	total: 2.22s	remaining: 614ms
160:	total: 2.54s	remaining: 300ms
179:	total: 2.88s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 15.1ms	remaining: 2.69s
20:	total: 370ms	remaining: 2.8s
40:	total: 683ms	remaining: 2.32s
60:	total: 993ms	remaining: 1.94s
80:	total: 1.32s	remaining: 1.61s
100:	total: 1.63s	remaining: 1.28s
120:	total: 1.92s	remaining: 938ms
140:	total: 2.23s	remaining: 616ms
160:	total: 2.53s	remaining: 299ms
179:	total: 2.83s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.8ms	remaining: 3.01s
20:	total: 335ms	remaining: 2.53s
40:	total: 647ms	remaining: 2.19s
60:	total: 970ms	remaining: 1.89s
80:	total: 1.3s	remaining: 1.58s
100:	total: 1.6s	remaining: 1.25s
120:	total: 1.92s	remaining: 935ms
140:	total: 2.23s	remaining: 618ms
160:	total: 2.54s	remaining: 300ms
179:	total: 2.83s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.1ms	remaining: 2.88s
20:	total: 327ms	remaining: 2.47s
40:	total: 644ms	remaining: 2.18s
60:	total: 978ms	remaining: 1.91s
80:	total: 1.3s	remaining: 1.59s
100:	total: 1.63s	remaining: 1.28s
120:	total: 1.96s	remaining: 954ms
140:	total: 2.29s	remaining: 633ms
160:	total: 2.61s	remaining: 308ms
179:	total: 2.9s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.4ms	remaining: 3.11s
20:	total: 332ms	remaining: 2.52s
40:	total: 647ms	remaining: 2.19s
60:	total: 949ms	remaining: 1.85s
80:	total: 1.24s	remaining: 1.51s
100:	total: 1.55s	remaining: 1.21s
120:	total: 1.85s	remaining: 903ms
140:	total: 2.16s	remaining: 597ms
160:	total: 2.48s	remaining: 293ms
179:	total: 2.79s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.3ms	remaining: 3.1s
20:	total: 335ms	remaining: 2.54s
40:	total: 662ms	remaining: 2.25s
60:	total: 1.01s	remaining: 1.96s
80:	total: 1.33s	remaining: 1.63s
100:	total: 1.66s	remaining: 1.3s
120:	total: 1.96s	remaining: 957ms
140:	total: 2.29s	remaining: 633ms
160:	total: 2.62s	remaining: 309ms
179:	total: 2.95s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.5ms	remaining: 3.49s
20:	total: 358ms	remaining: 2.71s
40:	total: 702ms	remaining: 2.38s
60:	total: 1.05s	remaining: 2.05s
80:	total: 1.37s	remaining: 1.67s
100:	total: 1.69s	remaining: 1.32s
120:	total: 2.03s	remaining: 989ms
140:	total: 2.37s	remaining: 655ms
160:	total: 2.69s	remaining: 318ms
179:	total: 3.01s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.6ms	remaining: 3.34s
20:	total: 341ms	remaining: 2.58s
40:	total: 659ms	remaining: 2.23s
60:	total: 978ms	remaining: 1.91s
80:	total: 1.29s	remaining: 1.58s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.92s	remaining: 937ms
140:	total: 2.24s	remaining: 620ms
160:	total: 2.58s	remaining: 304ms
179:	total: 2.88s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.2ms	remaining: 3.25s
20:	total: 352ms	remaining: 2.66s
40:	total: 683ms	remaining: 2.32s
60:	total: 1.03s	remaining: 2.01s
80:	total: 1.4s	remaining: 1.71s
100:	total: 1.74s	remaining: 1.36s
120:	total: 2.08s	remaining: 1.01s
140:	total: 2.46s	remaining: 680ms
160:	total: 2.8s	remaining: 330ms
179:	total: 3.15s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.7ms	remaining: 2.99s
20:	total: 334ms	remaining: 2.52s
40:	total: 662ms	remaining: 2.24s
60:	total: 973ms	remaining: 1.9s
80:	total: 1.29s	remaining: 1.58s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.93s	remaining: 940ms
140:	total: 2.24s	remaining: 619ms
160:	total: 2.56s	remaining: 302ms
179:	total: 2.87s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.5ms	remaining: 3.67s
20:	total: 394ms	remaining: 2.98s
40:	total: 757ms	remaining: 2.57s
60:	total: 1.13s	remaining: 2.19s
80:	total: 1.46s	remaining: 1.78s
100:	total: 1.84s	remaining: 1.44s
120:	total: 2.22s	remaining: 1.08s
140:	total: 2.6s	remaining: 719ms
160:	total: 2.96s	remaining: 349ms
179:	total: 3.3s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.7ms	remaining: 3.35s
20:	total: 388ms	remaining: 2.94s
40:	total: 785ms	remaining: 2.66s
60:	total: 1.13s	remaining: 2.21s
80:	total: 1.48s	remaining: 1.81s
100:	total: 1.81s	remaining: 1.42s
120:	total: 2.15s	remaining: 1.05s
140:	total: 2.5s	remaining: 692ms
160:	total: 2.83s	remaining: 334ms
179:	total: 3.17s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.6ms	remaining: 3.5s
20:	total: 343ms	remaining: 2.6s
40:	total: 680ms	remaining: 2.31s
60:	total: 1.01s	remaining: 1.96s
80:	total: 1.34s	remaining: 1.64s
100:	total: 1.68s	remaining: 1.31s
120:	total: 2.03s	remaining: 989ms
140:	total: 2.39s	remaining: 661ms
160:	total: 2.75s	remaining: 325ms
179:	total: 3.1s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22.6ms	remaining: 4.04s
20:	total: 348ms	remaining: 2.63s
40:	total: 686ms	remaining: 2.33s
60:	total: 1.01s	remaining: 1.98s
80:	total: 1.35s	remaining: 1.65s
100:	total: 1.68s	remaining: 1.31s
120:	total: 2.02s	remaining: 986ms
140:	total: 2.4s	remaining: 663ms
160:	total: 2.75s	remaining: 324ms
179:	total: 3.07s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19ms	remaining: 3.4s
20:	total: 359ms	remaining: 2.72s
40:	total: 697ms	remaining: 2.36s
60:	total: 1.02s	remaining: 2s
80:	total: 1.36s	remaining: 1.67s
100:	total: 1.71s	remaining: 1.34s
120:	total: 2.06s	remaining: 1s
140:	total: 2.4s	remaining: 665ms
160:	total: 2.74s	remaining: 324ms
179:	total: 3.08s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.4ms	remaining: 3.3s
20:	total: 351ms	remaining: 2.65s
40:	total: 685ms	remaining: 2.32s
60:	total: 1.03s	remaining: 2.01s
80:	total: 1.37s	remaining: 1.68s
100:	total: 1.73s	remaining: 1.35s
120:	total: 2.07s	remaining: 1.01s
140:	total: 2.41s	remaining: 667ms
160:	total: 2.74s	remaining: 324ms
179:	total: 3.06s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.5ms	remaining: 3.12s
20:	total: 363ms	remaining: 2.75s
40:	total: 704ms	remaining: 2.39s
60:	total: 1.04s	remaining: 2.03s
80:	total: 1.38s	remaining: 1.68s
100:	total: 1.73s	remaining: 1.35s
120:	total: 2.07s	remaining: 1.01s
140:	total: 2.41s	remaining: 668ms
160:	total: 2.77s	remaining: 326ms
179:	total: 3.09s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.1ms	remaining: 3.42s
20:	total: 345ms	remaining: 2.61s
40:	total: 707ms	remaining: 2.4s
60:	total: 1.05s	remaining: 2.06s
80:	total: 1.4s	remaining: 1.71s
100:	total: 1.76s	remaining: 1.38s
120:	total: 2.1s	remaining: 1.02s
140:	total: 2.47s	remaining: 684ms
160:	total: 2.82s	remaining: 333ms
179:	total: 3.17s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20ms	remaining: 3.58s
20:	total: 374ms	remaining: 2.83s
40:	total: 711ms	remaining: 2.41s
60:	total: 1.07s	remaining: 2.09s
80:	total: 1.44s	remaining: 1.75s
100:	total: 1.78s	remaining: 1.39s
120:	total: 2.13s	remaining: 1.04s
140:	total: 2.54s	remaining: 701ms
160:	total: 2.88s	remaining: 340ms
179:	total: 3.25s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.5ms	remaining: 3.32s
20:	total: 374ms	remaining: 2.83s
40:	total: 718ms	remaining: 2.43s
60:	total: 1.05s	remaining: 2.04s
80:	total: 1.41s	remaining: 1.72s
100:	total: 1.76s	remaining: 1.38s
120:	total: 2.11s	remaining: 1.03s
140:	total: 2.48s	remaining: 687ms
160:	total: 2.84s	remaining: 335ms
179:	total: 3.17s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.8ms	remaining: 3.73s
20:	total: 359ms	remaining: 2.72s
40:	total: 690ms	remaining: 2.34s
60:	total: 1.04s	remaining: 2.03s
80:	total: 1.38s	remaining: 1.69s
100:	total: 1.72s	remaining: 1.35s
120:	total: 2.09s	remaining: 1.02s
140:	total: 2.44s	remaining: 674ms
160:	total: 2.81s	remaining: 331ms
179:	total: 3.15s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19ms	remaining: 3.4s
20:	total: 380ms	remaining: 2.88s
40:	total: 711ms	remaining: 2.41s
60:	total: 1.04s	remaining: 2.03s
80:	total: 1.38s	remaining: 1.69s
100:	total: 1.71s	remaining: 1.34s
120:	total: 2.05s	remaining: 998ms
140:	total: 2.38s	remaining: 659ms
160:	total: 2.75s	remaining: 325ms
179:	total: 3.1s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.8ms	remaining: 3.72s
20:	total: 366ms	remaining: 2.77s
40:	total: 711ms	remaining: 2.41s
60:	total: 1.04s	remaining: 2.02s
80:	total: 1.37s	remaining: 1.68s
100:	total: 1.72s	remaining: 1.35s
120:	total: 2.06s	remaining: 1s
140:	total: 2.4s	remaining: 663ms
160:	total: 2.73s	remaining: 323ms
179:	total: 3.08s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22.3ms	remaining: 3.99s
20:	total: 377ms	remaining: 2.85s
40:	total: 717ms	remaining: 2.43s
60:	total: 1.07s	remaining: 2.09s
80:	total: 1.43s	remaining: 1.75s
100:	total: 1.76s	remaining: 1.38s
120:	total: 2.18s	remaining: 1.06s
140:	total: 2.52s	remaining: 696ms
160:	total: 2.87s	remaining: 338ms
179:	total: 3.29s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21ms	remaining: 3.77s
20:	total: 387ms	remaining: 2.93s
40:	total: 753ms	remaining: 2.55s
60:	total: 1.11s	remaining: 2.16s
80:	total: 1.44s	remaining: 1.76s
100:	total: 1.78s	remaining: 1.39s
120:	total: 2.11s	remaining: 1.03s
140:	total: 2.46s	remaining: 680ms
160:	total: 2.8s	remaining: 331ms
179:	total: 3.14s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.7ms	remaining: 3.17s
20:	total: 358ms	remaining: 2.71s
40:	total: 711ms	remaining: 2.41s
60:	total: 1.4s	remaining: 2.73s
80:	total: 1.75s	remaining: 2.14s
100:	total: 2.11s	remaining: 1.65s
120:	total: 2.47s	remaining: 1.2s
140:	total: 2.84s	remaining: 786ms
160:	total: 3.17s	remaining: 374ms
179:	total: 3.49s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22.1ms	remaining: 3.96s
20:	total: 408ms	remaining: 3.09s
40:	total: 795ms	remaining: 2.69s
60:	total: 1.17s	remaining: 2.29s
80:	total: 1.56s	remaining: 1.91s
100:	total: 1.96s	remaining: 1.53s
120:	total: 2.39s	remaining: 1.17s
140:	total: 2.81s	remaining: 778ms
160:	total: 3.17s	remaining: 375ms
179:	total: 3.52s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.9ms	remaining: 3.56s
20:	total: 388ms	remaining: 2.94s
40:	total: 751ms	remaining: 2.55s
60:	total: 1.15s	remaining: 2.25s
80:	total: 1.84s	remaining: 2.25s
100:	total: 2.23s	remaining: 1.74s
120:	total: 2.97s	remaining: 1.45s
140:	total: 3.69s	remaining: 1.02s
160:	total: 4.12s	remaining: 487ms
179:	total: 4.49s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.8ms	remaining: 3.54s
20:	total: 409ms	remaining: 3.09s
40:	total: 801ms	remaining: 2.72s
60:	total: 1.25s	remaining: 2.44s
80:	total: 1.69s	remaining: 2.07s
100:	total: 2.11s	remaining: 1.65s
120:	total: 2.52s	remaining: 1.23s
140:	total: 2.92s	remaining: 807ms
160:	total: 3.31s	remaining: 390ms
179:	total: 3.65s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.5ms	remaining: 3.5s
20:	total: 388ms	remaining: 2.94s
40:	total: 746ms	remaining: 2.53s
60:	total: 1.11s	remaining: 2.16s
80:	total: 1.46s	remaining: 1.78s
100:	total: 1.83s	remaining: 1.43s
120:	total: 2.19s	remaining: 1.07s
140:	total: 2.55s	remaining: 706ms
160:	total: 2.93s	remaining: 346ms
179:	total: 3.3s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19ms	remaining: 3.39s
20:	total: 376ms	remaining: 2.85s
40:	total: 724ms	remaining: 2.45s
60:	total: 1.11s	remaining: 2.17s
80:	total: 1.47s	remaining: 1.8s
100:	total: 1.83s	remaining: 1.43s
120:	total: 2.21s	remaining: 1.08s
140:	total: 2.59s	remaining: 716ms
160:	total: 2.96s	remaining: 349ms
179:	total: 3.31s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21.5ms	remaining: 3.85s
20:	total: 414ms	remaining: 3.14s
40:	total: 765ms	remaining: 2.59s
60:	total: 1.12s	remaining: 2.19s
80:	total: 1.48s	remaining: 1.8s
100:	total: 1.84s	remaining: 1.44s
120:	total: 2.21s	remaining: 1.08s
140:	total: 2.56s	remaining: 709ms
160:	total: 2.93s	remaining: 346ms
179:	total: 3.28s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22.5ms	remaining: 4.03s
20:	total: 383ms	remaining: 2.9s
40:	total: 767ms	remaining: 2.6s
60:	total: 1.16s	remaining: 2.27s
80:	total: 1.51s	remaining: 1.85s
100:	total: 1.88s	remaining: 1.47s
120:	total: 2.25s	remaining: 1.1s
140:	total: 2.62s	remaining: 724ms
160:	total: 3s	remaining: 354ms
179:	total: 3.34s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.8ms	remaining: 3.72s
20:	total: 385ms	remaining: 2.92s
40:	total: 744ms	remaining: 2.52s
60:	total: 1.09s	remaining: 2.14s
80:	total: 1.44s	remaining: 1.75s
100:	total: 1.78s	remaining: 1.4s
120:	total: 2.12s	remaining: 1.03s
140:	total: 2.46s	remaining: 681ms
160:	total: 2.87s	remaining: 338ms
179:	total: 3.2s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22.2ms	remaining: 3.98s
20:	total: 360ms	remaining: 2.73s
40:	total: 702ms	remaining: 2.38s
60:	total: 1.04s	remaining: 2.03s
80:	total: 1.39s	remaining: 1.7s
100:	total: 1.71s	remaining: 1.34s
120:	total: 2.05s	remaining: 998ms
140:	total: 2.4s	remaining: 663ms
160:	total: 2.75s	remaining: 325ms
179:	total: 3.08s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19ms	remaining: 3.4s
20:	total: 383ms	remaining: 2.9s
40:	total: 713ms	remaining: 2.42s
60:	total: 1.03s	remaining: 2.02s
80:	total: 1.36s	remaining: 1.66s
100:	total: 1.69s	remaining: 1.32s
120:	total: 2.02s	remaining: 987ms
140:	total: 2.37s	remaining: 656ms
160:	total: 2.73s	remaining: 322ms
179:	total: 3.05s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.6ms	remaining: 3.5s
20:	total: 357ms	remaining: 2.7s
40:	total: 702ms	remaining: 2.38s
60:	total: 1.04s	remaining: 2.03s
80:	total: 1.38s	remaining: 1.68s
100:	total: 1.73s	remaining: 1.35s
120:	total: 2.08s	remaining: 1.01s
140:	total: 2.44s	remaining: 676ms
160:	total: 2.81s	remaining: 332ms
179:	total: 3.16s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.2ms	remaining: 3.43s
20:	total: 356ms	remaining: 2.69s
40:	total: 723ms	remaining: 2.45s
60:	total: 1.05s	remaining: 2.05s
80:	total: 1.39s	remaining: 1.7s
100:	total: 1.72s	remaining: 1.35s
120:	total: 2.08s	remaining: 1.01s
140:	total: 2.44s	remaining: 674ms
160:	total: 2.8s	remaining: 330ms
179:	total: 3.13s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.9ms	remaining: 3.56s
20:	total: 349ms	remaining: 2.64s
40:	total: 685ms	remaining: 2.32s
60:	total: 1.04s	remaining: 2.03s
80:	total: 1.36s	remaining: 1.67s
100:	total: 1.69s	remaining: 1.32s
120:	total: 2.02s	remaining: 987ms
140:	total: 2.35s	remaining: 652ms
160:	total: 2.69s	remaining: 318ms
179:	total: 3.03s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.7ms	remaining: 3.35s
20:	total: 374ms	remaining: 2.83s
40:	total: 723ms	remaining: 2.45s
60:	total: 1.06s	remaining: 2.06s
80:	total: 1.42s	remaining: 1.74s
100:	total: 1.76s	remaining: 1.38s
120:	total: 2.08s	remaining: 1.02s
140:	total: 2.42s	remaining: 670ms
160:	total: 2.77s	remaining: 327ms
179:	total: 3.09s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.2ms	remaining: 3.43s
20:	total: 373ms	remaining: 2.82s
40:	total: 730ms	remaining: 2.47s
60:	total: 1.06s	remaining: 2.07s
80:	total: 1.42s	remaining: 1.73s
100:	total: 1.75s	remaining: 1.37s
120:	total: 2.1s	remaining: 1.02s
140:	total: 2.44s	remaining: 674ms
160:	total: 2.78s	remaining: 328ms
179:	total: 3.13s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.5ms	remaining: 3.31s
20:	total: 362ms	remaining: 2.74s
40:	total: 728ms	remaining: 2.47s
60:	total: 1.08s	remaining: 2.11s
80:	total: 1.43s	remaining: 1.75s
100:	total: 1.77s	remaining: 1.39s
120:	total: 2.1s	remaining: 1.02s
140:	total: 2.43s	remaining: 671ms
160:	total: 2.77s	remaining: 327ms
179:	total: 3.1s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.6ms	remaining: 3.32s
20:	total: 355ms	remaining: 2.69s
40:	total: 688ms	remaining: 2.33s
60:	total: 1.01s	remaining: 1.98s
80:	total: 1.34s	remaining: 1.64s
100:	total: 1.67s	remaining: 1.3s
120:	total: 2s	remaining: 978ms
140:	total: 2.34s	remaining: 648ms
160:	total: 2.69s	remaining: 317ms
179:	total: 3.01s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.3ms	remaining: 3.27s
20:	total: 345ms	remaining: 2.61s
40:	total: 686ms	remaining: 2.33s
60:	total: 1.03s	remaining: 2s
80:	total: 1.38s	remaining: 1.68s
100:	total: 1.72s	remaining: 1.34s
120:	total: 2.07s	remaining: 1.01s
140:	total: 2.42s	remaining: 668ms
160:	total: 2.76s	remaining: 326ms
179:	total: 3.08s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.9ms	remaining: 3.21s
20:	total: 341ms	remaining: 2.58s
40:	total: 672ms	remaining: 2.28s
60:	total: 1s	remaining: 1.96s
80:	total: 1.34s	remaining: 1.64s
100:	total: 1.67s	remaining: 1.31s
120:	total: 2.01s	remaining: 980ms
140:	total: 2.35s	remaining: 650ms
160:	total: 2.69s	remaining: 318ms
179:	total: 3.01s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19ms	remaining: 3.39s
20:	total: 352ms	remaining: 2.66s
40:	total: 693ms	remaining: 2.35s
60:	total: 1.02s	remaining: 1.99s
80:	total: 1.34s	remaining: 1.64s
100:	total: 1.72s	remaining: 1.34s
120:	total: 2.11s	remaining: 1.03s
140:	total: 2.53s	remaining: 700ms
160:	total: 2.96s	remaining: 349ms
179:	total: 3.33s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.4ms	remaining: 3.48s
20:	total: 396ms	remaining: 3s
40:	total: 794ms	remaining: 2.69s
60:	total: 1.15s	remaining: 2.25s
80:	total: 1.53s	remaining: 1.87s
100:	total: 1.92s	remaining: 1.5s
120:	total: 2.27s	remaining: 1.11s
140:	total: 2.63s	remaining: 729ms
160:	total: 2.98s	remaining: 352ms
179:	total: 3.3s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.2ms	remaining: 3.26s
20:	total: 348ms	remaining: 2.63s
40:	total: 678ms	remaining: 2.3s
60:	total: 1.01s	remaining: 1.98s
80:	total: 1.33s	remaining: 1.63s
100:	total: 1.66s	remaining: 1.29s
120:	total: 1.99s	remaining: 972ms
140:	total: 2.33s	remaining: 646ms
160:	total: 2.68s	remaining: 317ms
179:	total: 3.01s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21.4ms	remaining: 3.83s
20:	total: 361ms	remaining: 2.73s
40:	total: 713ms	remaining: 2.42s
60:	total: 1.04s	remaining: 2.02s
80:	total: 1.37s	remaining: 1.68s
100:	total: 1.7s	remaining: 1.33s
120:	total: 2.05s	remaining: 999ms
140:	total: 2.38s	remaining: 659ms
160:	total: 2.75s	remaining: 324ms
179:	total: 3.07s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.2ms	remaining: 3.62s
20:	total: 342ms	remaining: 2.59s
40:	total: 668ms	remaining: 2.27s
60:	total: 1.01s	remaining: 1.97s
80:	total: 1.33s	remaining: 1.63s
100:	total: 1.67s	remaining: 1.3s
120:	total: 1.99s	remaining: 969ms
140:	total: 2.32s	remaining: 641ms
160:	total: 2.66s	remaining: 314ms
179:	total: 2.97s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.3ms	remaining: 3.28s
20:	total: 356ms	remaining: 2.7s
40:	total: 696ms	remaining: 2.36s
60:	total: 1.04s	remaining: 2.03s
80:	total: 1.36s	remaining: 1.67s
100:	total: 1.71s	remaining: 1.34s
120:	total: 2.05s	remaining: 998ms
140:	total: 2.38s	remaining: 657ms
160:	total: 2.72s	remaining: 321ms
179:	total: 3.06s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.3ms	remaining: 3.63s
20:	total: 349ms	remaining: 2.64s
40:	total: 675ms	remaining: 2.29s
60:	total: 1.01s	remaining: 1.97s
80:	total: 1.35s	remaining: 1.65s
100:	total: 1.68s	remaining: 1.31s
120:	total: 2.01s	remaining: 981ms
140:	total: 2.37s	remaining: 655ms
160:	total: 2.71s	remaining: 320ms
179:	total: 3.05s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.8ms	remaining: 3.37s
20:	total: 350ms	remaining: 2.65s
40:	total: 704ms	remaining: 2.39s
60:	total: 1.04s	remaining: 2.04s
80:	total: 1.37s	remaining: 1.67s
100:	total: 1.73s	remaining: 1.36s
120:	total: 2.15s	remaining: 1.05s
140:	total: 2.54s	remaining: 703ms
160:	total: 2.97s	remaining: 350ms
179:	total: 3.35s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21.4ms	remaining: 3.83s
20:	total: 396ms	remaining: 3s
40:	total: 733ms	remaining: 2.48s
60:	total: 1.09s	remaining: 2.14s
80:	total: 1.43s	remaining: 1.75s
100:	total: 1.76s	remaining: 1.38s
120:	total: 2.1s	remaining: 1.02s
140:	total: 2.43s	remaining: 672ms
160:	total: 2.78s	remaining: 328ms
179:	total: 3.1s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.4ms	remaining: 3.11s
20:	total: 355ms	remaining: 2.69s
40:	total: 686ms	remaining: 2.32s
60:	total: 1s	remaining: 1.96s
80:	total: 1.35s	remaining: 1.65s
100:	total: 1.68s	remaining: 1.31s
120:	total: 2.01s	remaining: 979ms
140:	total: 2.38s	remaining: 659ms
160:	total: 2.73s	remaining: 322ms
179:	total: 3.05s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.7ms	remaining: 3.17s
20:	total: 359ms	remaining: 2.72s
40:	total: 698ms	remaining: 2.37s
60:	total: 1.04s	remaining: 2.03s
80:	total: 1.37s	remaining: 1.67s
100:	total: 1.69s	remaining: 1.32s
120:	total: 2.01s	remaining: 981ms
140:	total: 2.35s	remaining: 651ms
160:	total: 2.71s	remaining: 320ms
179:	total: 3.03s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21.3ms	remaining: 3.81s
20:	total: 386ms	remaining: 2.92s
40:	total: 745ms	remaining: 2.52s
60:	total: 1.11s	remaining: 2.16s
80:	total: 1.47s	remaining: 1.8s
100:	total: 1.83s	remaining: 1.43s
120:	total: 2.21s	remaining: 1.08s
140:	total: 2.59s	remaining: 717ms
160:	total: 2.96s	remaining: 349ms
179:	total: 3.33s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.2ms	remaining: 3.61s
20:	total: 427ms	remaining: 3.23s
40:	total: 829ms	remaining: 2.81s
60:	total: 1.22s	remaining: 2.37s
80:	total: 1.62s	remaining: 1.98s
100:	total: 1.99s	remaining: 1.55s
120:	total: 2.36s	remaining: 1.15s
140:	total: 2.74s	remaining: 759ms
160:	total: 3.11s	remaining: 367ms
179:	total: 3.47s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 26.9ms	remaining: 4.82s
20:	total: 402ms	remaining: 3.04s
40:	total: 792ms	remaining: 2.69s
60:	total: 1.17s	remaining: 2.28s
80:	total: 1.55s	remaining: 1.9s
100:	total: 1.92s	remaining: 1.5s
120:	total: 2.29s	remaining: 1.12s
140:	total: 2.67s	remaining: 739ms
160:	total: 3.03s	remaining: 358ms
179:	total: 3.38s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.7ms	remaining: 3.52s
20:	total: 396ms	remaining: 3s
40:	total: 770ms	remaining: 2.61s
60:	total: 1.13s	remaining: 2.21s
80:	total: 1.51s	remaining: 1.84s
100:	total: 1.87s	remaining: 1.47s
120:	total: 2.24s	remaining: 1.09s
140:	total: 2.62s	remaining: 725ms
160:	total: 3.01s	remaining: 356ms
179:	total: 3.37s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.7ms	remaining: 3.71s
20:	total: 401ms	remaining: 3.03s
40:	total: 800ms	remaining: 2.71s
60:	total: 1.17s	remaining: 2.29s
80:	total: 1.54s	remaining: 1.88s
100:	total: 1.92s	remaining: 1.5s
120:	total: 2.27s	remaining: 1.11s
140:	total: 2.64s	remaining: 730ms
160:	total: 3.02s	remaining: 357ms
179:	total: 3.38s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21.2ms	remaining: 3.8s
20:	total: 391ms	remaining: 2.96s
40:	total: 753ms	remaining: 2.55s
60:	total: 1.16s	remaining: 2.26s
80:	total: 1.54s	remaining: 1.88s
100:	total: 1.91s	remaining: 1.49s
120:	total: 2.29s	remaining: 1.12s
140:	total: 2.66s	remaining: 737ms
160:	total: 3.06s	remaining: 361ms
179:	total: 3.42s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.7ms	remaining: 3.52s
20:	total: 406ms	remaining: 3.07s
40:	total: 767ms	remaining: 2.6s
60:	total: 1.14s	remaining: 2.23s
80:	total: 1.52s	remaining: 1.85s
100:	total: 1.88s	remaining: 1.47s
120:	total: 2.25s	remaining: 1.1s
140:	total: 2.62s	remaining: 724ms
160:	total: 2.98s	remaining: 352ms
179:	total: 3.34s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21.7ms	remaining: 3.88s
20:	total: 416ms	remaining: 3.15s
40:	total: 835ms	remaining: 2.83s
60:	total: 1.25s	remaining: 2.43s
80:	total: 1.65s	remaining: 2.02s
100:	total: 2.02s	remaining: 1.58s
120:	total: 2.38s	remaining: 1.16s
140:	total: 2.79s	remaining: 772ms
160:	total: 3.2s	remaining: 378ms
179:	total: 3.56s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.4ms	remaining: 3.46s
20:	total: 426ms	remaining: 3.22s
40:	total: 767ms	remaining: 2.6s
60:	total: 1.17s	remaining: 2.29s
80:	total: 1.54s	remaining: 1.88s
100:	total: 1.91s	remaining: 1.49s
120:	total: 2.27s	remaining: 1.11s
140:	total: 2.64s	remaining: 731ms
160:	total: 3.02s	remaining: 357ms
179:	total: 3.39s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.6ms	remaining: 3.69s
20:	total: 416ms	remaining: 3.15s
40:	total: 795ms	remaining: 2.69s
60:	total: 1.15s	remaining: 2.25s
80:	total: 1.54s	remaining: 1.88s
100:	total: 1.92s	remaining: 1.5s
120:	total: 2.31s	remaining: 1.13s
140:	total: 2.74s	remaining: 758ms
160:	total: 3.14s	remaining: 370ms
179:	total: 3.51s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 24.2ms	remaining: 4.32s
20:	total: 405ms	remaining: 3.07s
40:	total: 767ms	remaining: 2.6s
60:	total: 1.13s	remaining: 2.19s
80:	total: 1.49s	remaining: 1.82s
100:	total: 1.86s	remaining: 1.45s
120:	total: 2.23s	remaining: 1.08s
140:	total: 2.6s	remaining: 720ms
160:	total: 3s	remaining: 354ms
179:	total: 3.35s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.7ms	remaining: 3.34s
20:	total: 384ms	remaining: 2.91s
40:	total: 756ms	remaining: 2.56s
60:	total: 1.11s	remaining: 2.17s
80:	total: 1.48s	remaining: 1.81s
100:	total: 1.82s	remaining: 1.43s
120:	total: 2.17s	remaining: 1.06s
140:	total: 2.52s	remaining: 698ms
160:	total: 2.9s	remaining: 342ms
179:	total: 3.27s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.2ms	remaining: 3.62s
20:	total: 416ms	remaining: 3.15s
40:	total: 814ms	remaining: 2.76s
60:	total: 1.21s	remaining: 2.36s
80:	total: 1.57s	remaining: 1.92s
100:	total: 1.95s	remaining: 1.53s
120:	total: 2.34s	remaining: 1.14s
140:	total: 2.73s	remaining: 754ms
160:	total: 3.11s	remaining: 367ms
179:	total: 3.47s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 24.2ms	remaining: 4.34s
20:	total: 412ms	remaining: 3.12s
40:	total: 786ms	remaining: 2.67s
60:	total: 1.17s	remaining: 2.28s
80:	total: 1.58s	remaining: 1.93s
100:	total: 1.97s	remaining: 1.54s
120:	total: 2.37s	remaining: 1.15s
140:	total: 2.77s	remaining: 767ms
160:	total: 3.18s	remaining: 376ms
179:	total: 3.56s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.2ms	remaining: 3.61s
20:	total: 389ms	remaining: 2.94s
40:	total: 760ms	remaining: 2.58s
60:	total: 1.14s	remaining: 2.23s
80:	total: 1.52s	remaining: 1.85s
100:	total: 1.89s	remaining: 1.48s
120:	total: 2.28s	remaining: 1.11s
140:	total: 2.66s	remaining: 736ms
160:	total: 3.06s	remaining: 361ms
179:	total: 3.43s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.9ms	remaining: 3.73s
20:	total: 401ms	remaining: 3.04s
40:	total: 761ms	remaining: 2.58s
60:	total: 1.13s	remaining: 2.2s
80:	total: 1.49s	remaining: 1.82s
100:	total: 1.85s	remaining: 1.45s
120:	total: 2.23s	remaining: 1.08s
140:	total: 2.61s	remaining: 723ms
160:	total: 2.99s	remaining: 353ms
179:	total: 3.36s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19ms	remaining: 3.4s
20:	total: 420ms	remaining: 3.18s
40:	total: 794ms	remaining: 2.69s
60:	total: 1.15s	remaining: 2.25s
80:	total: 1.52s	remaining: 1.86s
100:	total: 1.91s	remaining: 1.49s
120:	total: 2.28s	remaining: 1.11s
140:	total: 2.67s	remaining: 737ms
160:	total: 3.06s	remaining: 361ms
179:	total: 3.41s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21.6ms	remaining: 3.87s
20:	total: 400ms	remaining: 3.03s
40:	total: 786ms	remaining: 2.66s
60:	total: 1.16s	remaining: 2.26s
80:	total: 1.53s	remaining: 1.86s
100:	total: 1.9s	remaining: 1.49s
120:	total: 2.27s	remaining: 1.1s
140:	total: 2.67s	remaining: 738ms
160:	total: 3.05s	remaining: 360ms
179:	total: 3.42s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22ms	remaining: 3.93s
20:	total: 390ms	remaining: 2.95s
40:	total: 772ms	remaining: 2.62s
60:	total: 1.15s	remaining: 2.25s
80:	total: 1.51s	remaining: 1.85s
100:	total: 1.89s	remaining: 1.48s
120:	total: 2.25s	remaining: 1.1s
140:	total: 2.63s	remaining: 727ms
160:	total: 3.02s	remaining: 356ms
179:	total: 3.37s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 23ms	remaining: 4.11s
20:	total: 403ms	remaining: 3.05s
40:	total: 820ms	remaining: 2.78s
60:	total: 1.23s	remaining: 2.41s
80:	total: 1.63s	remaining: 1.99s
100:	total: 2.01s	remaining: 1.58s
120:	total: 2.38s	remaining: 1.16s
140:	total: 2.76s	remaining: 763ms
160:	total: 3.15s	remaining: 371ms
179:	total: 3.51s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.6ms	remaining: 3.51s
20:	total: 383ms	remaining: 2.9s
40:	total: 769ms	remaining: 2.6s
60:	total: 1.14s	remaining: 2.22s
80:	total: 1.5s	remaining: 1.83s
100:	total: 1.88s	remaining: 1.47s
120:	total: 2.23s	remaining: 1.09s
140:	total: 2.6s	remaining: 720ms
160:	total: 2.99s	remaining: 353ms
179:	total: 3.35s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.1ms	remaining: 3.42s
20:	total: 393ms	remaining: 2.98s
40:	total: 778ms	remaining: 2.64s
60:	total: 1.18s	remaining: 2.3s
80:	total: 1.57s	remaining: 1.92s
100:	total: 1.96s	remaining: 1.53s
120:	total: 2.34s	remaining: 1.14s
140:	total: 2.74s	remaining: 758ms
160:	total: 3.13s	remaining: 369ms
179:	total: 3.5s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22.4ms	remaining: 4.02s
20:	total: 408ms	remaining: 3.09s
40:	total: 797ms	remaining: 2.7s
60:	total: 1.18s	remaining: 2.31s
80:	total: 1.59s	remaining: 1.94s
100:	total: 1.99s	remaining: 1.56s
120:	total: 2.4s	remaining: 1.17s
140:	total: 2.8s	remaining: 775ms
160:	total: 3.25s	remaining: 384ms
179:	total: 3.62s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22.5ms	remaining: 4.02s
20:	total: 392ms	remaining: 2.97s
40:	total: 758ms	remaining: 2.57s
60:	total: 1.14s	remaining: 2.22s
80:	total: 1.51s	remaining: 1.84s
100:	total: 1.88s	remaining: 1.47s
120:	total: 2.25s	remaining: 1.09s
140:	total: 2.62s	remaining: 724ms
160:	total: 3.01s	remaining: 355ms
179:	total: 3.36s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22.9ms	remaining: 4.1s
20:	total: 442ms	remaining: 3.35s
40:	total: 843ms	remaining: 2.86s
60:	total: 1.24s	remaining: 2.42s
80:	total: 1.66s	remaining: 2.03s
100:	total: 2.07s	remaining: 1.62s
120:	total: 2.47s	remaining: 1.2s
140:	total: 2.85s	remaining: 788ms
160:	total: 3.26s	remaining: 384ms
179:	total: 3.64s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 25ms	remaining: 4.47s
20:	total: 436ms	remaining: 3.3s
40:	total: 813ms	remaining: 2.76s
60:	total: 1.2s	remaining: 2.34s
80:	total: 1.57s	remaining: 1.92s
100:	total: 1.98s	remaining: 1.54s
120:	total: 2.35s	remaining: 1.15s
140:	total: 2.73s	remaining: 756ms
160:	total: 3.12s	remaining: 369ms
179:	total: 3.49s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 23ms	remaining: 4.12s
20:	total: 431ms	remaining: 3.26s
40:	total: 882ms	remaining: 2.99s
60:	total: 1.3s	remaining: 2.54s
80:	total: 1.72s	remaining: 2.11s
100:	total: 2.15s	remaining: 1.68s
120:	total: 2.55s	remaining: 1.24s
140:	total: 2.95s	remaining: 816ms
160:	total: 3.34s	remaining: 394ms
179:	total: 3.7s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.6ms	remaining: 3.32s
20:	total: 394ms	remaining: 2.98s
40:	total: 788ms	remaining: 2.67s
60:	total: 1.17s	remaining: 2.29s
80:	total: 1.54s	remaining: 1.88s
100:	total: 1.93s	remaining: 1.51s
120:	total: 2.31s	remaining: 1.13s
140:	total: 2.7s	remaining: 747ms
160:	total: 3.1s	remaining: 366ms
179:	total: 3.45s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 23ms	remaining: 4.11s
20:	total: 440ms	remaining: 3.33s
40:	total: 856ms	remaining: 2.9s
60:	total: 1.26s	remaining: 2.46s
80:	total: 1.67s	remaining: 2.04s
100:	total: 2.08s	remaining: 1.62s
120:	total: 2.48s	remaining: 1.21s
140:	total: 2.92s	remaining: 808ms
160:	total: 3.33s	remaining: 393ms
179:	total: 3.7s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.8ms	remaining: 3.55s
20:	total: 392ms	remaining: 2.97s
40:	total: 773ms	remaining: 2.62s
60:	total: 1.15s	remaining: 2.25s
80:	total: 1.51s	remaining: 1.85s
100:	total: 1.85s	remaining: 1.45s
120:	total: 2.23s	remaining: 1.09s
140:	total: 2.61s	remaining: 722ms
160:	total: 3s	remaining: 355ms
179:	total: 3.36s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19ms	remaining: 3.4s
20:	total: 377ms	remaining: 2.86s
40:	total: 740ms	remaining: 2.51s
60:	total: 1.12s	remaining: 2.18s
80:	total: 1.47s	remaining: 1.8s
100:	total: 1.86s	remaining: 1.46s
120:	total: 2.25s	remaining: 1.1s
140:	total: 2.63s	remaining: 727ms
160:	total: 3.02s	remaining: 356ms
179:	total: 3.38s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.7ms	remaining: 3.52s
20:	total: 406ms	remaining: 3.07s
40:	total: 785ms	remaining: 2.66s
60:	total: 1.15s	remaining: 2.25s
80:	total: 1.54s	remaining: 1.88s
100:	total: 1.91s	remaining: 1.49s
120:	total: 2.3s	remaining: 1.12s
140:	total: 2.66s	remaining: 737ms
160:	total: 3.04s	remaining: 359ms
179:	total: 3.42s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.9ms	remaining: 3.39s
20:	total: 375ms	remaining: 2.84s
40:	total: 733ms	remaining: 2.48s
60:	total: 1.1s	remaining: 2.16s
80:	total: 1.49s	remaining: 1.82s
100:	total: 1.84s	remaining: 1.44s
120:	total: 2.21s	remaining: 1.08s
140:	total: 2.57s	remaining: 711ms
160:	total: 2.93s	remaining: 346ms
179:	total: 3.29s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.6ms	remaining: 3.51s
20:	total: 386ms	remaining: 2.92s
40:	total: 749ms	remaining: 2.54s
60:	total: 1.1s	remaining: 2.16s
80:	total: 1.47s	remaining: 1.8s
100:	total: 1.84s	remaining: 1.44s
120:	total: 2.2s	remaining: 1.07s
140:	total: 2.57s	remaining: 711ms
160:	total: 2.93s	remaining: 346ms
179:	total: 3.3s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22.5ms	remaining: 4.03s
20:	total: 368ms	remaining: 2.79s
40:	total: 761ms	remaining: 2.58s
60:	total: 1.18s	remaining: 2.29s
80:	total: 1.55s	remaining: 1.9s
100:	total: 1.91s	remaining: 1.5s
120:	total: 2.29s	remaining: 1.11s
140:	total: 2.67s	remaining: 739ms
160:	total: 3.05s	remaining: 360ms
179:	total: 3.41s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.5ms	remaining: 3.68s
20:	total: 409ms	remaining: 3.09s
40:	total: 787ms	remaining: 2.67s
60:	total: 1.16s	remaining: 2.25s
80:	total: 1.51s	remaining: 1.85s
100:	total: 1.89s	remaining: 1.48s
120:	total: 2.26s	remaining: 1.1s
140:	total: 2.63s	remaining: 727ms
160:	total: 3s	remaining: 354ms
179:	total: 3.35s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.8ms	remaining: 3.55s
20:	total: 379ms	remaining: 2.87s
40:	total: 829ms	remaining: 2.81s
60:	total: 1.21s	remaining: 2.36s
80:	total: 1.63s	remaining: 1.99s
100:	total: 2.03s	remaining: 1.59s
120:	total: 2.43s	remaining: 1.18s
140:	total: 2.81s	remaining: 777ms
160:	total: 3.2s	remaining: 378ms
179:	total: 3.55s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22.7ms	remaining: 4.06s
20:	total: 412ms	remaining: 3.12s
40:	total: 788ms	remaining: 2.67s
60:	total: 1.16s	remaining: 2.26s
80:	total: 1.53s	remaining: 1.87s
100:	total: 1.9s	remaining: 1.49s
120:	total: 2.27s	remaining: 1.11s
140:	total: 2.64s	remaining: 730ms
160:	total: 3.01s	remaining: 355ms
179:	total: 3.37s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.5ms	remaining: 3.67s
20:	total: 407ms	remaining: 3.08s
40:	total: 784ms	remaining: 2.66s
60:	total: 1.15s	remaining: 2.23s
80:	total: 1.51s	remaining: 1.84s
100:	total: 1.89s	remaining: 1.48s
120:	total: 2.28s	remaining: 1.11s
140:	total: 2.68s	remaining: 742ms
160:	total: 3.08s	remaining: 363ms
179:	total: 3.44s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.3ms	remaining: 3.45s
20:	total: 392ms	remaining: 2.97s
40:	total: 764ms	remaining: 2.59s
60:	total: 1.14s	remaining: 2.22s
80:	total: 1.53s	remaining: 1.86s
100:	total: 1.9s	remaining: 1.49s
120:	total: 2.27s	remaining: 1.11s
140:	total: 2.66s	remaining: 736ms
160:	total: 3.04s	remaining: 359ms
179:	total: 3.39s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21.2ms	remaining: 3.79s
20:	total: 381ms	remaining: 2.88s
40:	total: 760ms	remaining: 2.58s
60:	total: 1.13s	remaining: 2.2s
80:	total: 1.5s	remaining: 1.83s
100:	total: 1.87s	remaining: 1.46s
120:	total: 2.25s	remaining: 1.09s
140:	total: 2.63s	remaining: 728ms
160:	total: 3.04s	remaining: 359ms
179:	total: 3.47s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 24.9ms	remaining: 4.46s
20:	total: 406ms	remaining: 3.07s
40:	total: 832ms	remaining: 2.82s
60:	total: 1.25s	remaining: 2.45s
80:	total: 1.67s	remaining: 2.04s
100:	total: 2.08s	remaining: 1.63s
120:	total: 2.48s	remaining: 1.21s
140:	total: 2.9s	remaining: 803ms
160:	total: 3.31s	remaining: 390ms
179:	total: 3.71s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.4ms	remaining: 3.65s
20:	total: 386ms	remaining: 2.93s
40:	total: 738ms	remaining: 2.5s
60:	total: 1.09s	remaining: 2.12s
80:	total: 1.43s	remaining: 1.74s
100:	total: 1.79s	remaining: 1.4s
120:	total: 2.18s	remaining: 1.06s
140:	total: 2.55s	remaining: 706ms
160:	total: 2.92s	remaining: 344ms
179:	total: 3.26s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21ms	remaining: 3.76s
20:	total: 383ms	remaining: 2.9s
40:	total: 748ms	remaining: 2.53s
60:	total: 1.11s	remaining: 2.17s
80:	total: 1.47s	remaining: 1.8s
100:	total: 1.85s	remaining: 1.45s
120:	total: 2.22s	remaining: 1.08s
140:	total: 2.59s	remaining: 716ms
160:	total: 2.97s	remaining: 351ms
179:	total: 3.32s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 24.9ms	remaining: 4.45s
20:	total: 399ms	remaining: 3.02s
40:	total: 773ms	remaining: 2.62s
60:	total: 1.16s	remaining: 2.27s
80:	total: 1.53s	remaining: 1.87s
100:	total: 1.91s	remaining: 1.49s
120:	total: 2.28s	remaining: 1.11s
140:	total: 2.64s	remaining: 731ms
160:	total: 3.03s	remaining: 358ms
179:	total: 3.41s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.4ms	remaining: 3.11s
20:	total: 337ms	remaining: 2.56s
40:	total: 647ms	remaining: 2.19s
60:	total: 950ms	remaining: 1.85s
80:	total: 1.26s	remaining: 1.54s
100:	total: 1.57s	remaining: 1.23s
120:	total: 1.92s	remaining: 937ms
140:	total: 2.33s	remaining: 644ms
160:	total: 2.69s	remaining: 318ms
179:	total: 3.04s	remaining: 0us


In [44]:
results["gap"] = results["mean_train_score"] - results["mean_test_score"]
params_df = results["params"].apply(pd.Series)

final_df = pd.concat([
    params_df,
    results[["mean_train_score","mean_test_score","gap"]]
], axis=1)

final_df.sort_values(
    ["mean_test_score","gap"],
    ascending=[False,True]
).head(10)

,depth,l2_leaf_reg,learning_rate,mean_train_score,mean_test_score,gap
7,2.0,40.0,0.05,0.920599,0.809685,0.110914
4,2.0,30.0,0.05,0.920818,0.808679,0.112139
1,2.0,20.0,0.05,0.922097,0.808519,0.113578
8,2.0,40.0,0.10,0.953657,0.807898,0.145759
10,3.0,20.0,0.05,0.963305,0.807830,0.155475
13,3.0,30.0,0.05,0.960202,0.807750,0.152452
16,3.0,40.0,0.05,0.957427,0.807549,0.149878
17,3.0,40.0,0.10,0.986296,0.807096,0.179199
14,3.0,30.0,0.10,0.988428,0.806761,0.181667
6,2.0,40.0,0.03,0.893576,0.806688,0.086888


**Nhận xét: depth = 2, lr = 0.05 tốt rõ rệt, l2_leaf_reg càng lớn càng tốt => tiếp tục tuning l2_leaf_reg, thử các lân cận của lr**

##### Lần 2

In [52]:
param_grid = {
    "depth": [2],
    "learning_rate": [0.03, 0.04, 0.05],
    "l2_leaf_reg": [40, 50, 60, 70],
}
gs1 = GridSearchCV(
    estimator=base_model,
    param_grid=param_grid,
    cv=5,
    scoring="roc_auc",
    return_train_score=True,
)

gs1.fit(X_train, y_train, cat_features=cat_features)

Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.1ms	remaining: 3.42s
20:	total: 367ms	remaining: 2.78s
40:	total: 744ms	remaining: 2.52s
60:	total: 1.11s	remaining: 2.16s
80:	total: 1.44s	remaining: 1.76s
100:	total: 1.79s	remaining: 1.4s
120:	total: 2.15s	remaining: 1.05s
140:	total: 2.51s	remaining: 695ms
160:	total: 2.82s	remaining: 332ms
179:	total: 3.15s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 21.8ms	remaining: 3.9s
20:	total: 391ms	remaining: 2.96s
40:	total: 758ms	remaining: 2.57s
60:	total: 1.09s	remaining: 2.12s
80:	total: 1.4s	remaining: 1.71s
100:	total: 1.71s	remaining: 1.34s
120:	total: 2.03s	remaining: 990ms
140:	total: 2.35s	remaining: 649ms
160:	total: 2.67s	remaining: 315ms
179:	total: 2.98s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 15.6ms	remaining: 2.78s
20:	total: 357ms	remaining: 2.71s
40:	total: 668ms	remaining: 2.26s
60:	total: 1.01s	remaining: 1.96s
80:	total: 1.31s	remaining: 1.61s
100:	total: 1.63s	remaining: 1.27s
120:	total: 1.96s	remaining: 955ms
140:	total: 2.3s	remaining: 636ms
160:	total: 2.62s	remaining: 309ms
179:	total: 2.94s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.1ms	remaining: 3.06s
20:	total: 350ms	remaining: 2.65s
40:	total: 709ms	remaining: 2.4s
60:	total: 1.04s	remaining: 2.03s
80:	total: 1.35s	remaining: 1.66s
100:	total: 1.68s	remaining: 1.32s
120:	total: 2.01s	remaining: 982ms
140:	total: 2.38s	remaining: 657ms
160:	total: 2.71s	remaining: 319ms
179:	total: 3.02s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.5ms	remaining: 3.49s
20:	total: 348ms	remaining: 2.63s
40:	total: 673ms	remaining: 2.28s
60:	total: 1.01s	remaining: 1.97s
80:	total: 1.39s	remaining: 1.7s
100:	total: 1.73s	remaining: 1.36s
120:	total: 2.08s	remaining: 1.01s
140:	total: 2.44s	remaining: 675ms
160:	total: 2.77s	remaining: 327ms
179:	total: 3.1s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.1ms	remaining: 3.42s
20:	total: 337ms	remaining: 2.55s
40:	total: 665ms	remaining: 2.25s
60:	total: 988ms	remaining: 1.93s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.66s	remaining: 1.3s
120:	total: 1.99s	remaining: 970ms
140:	total: 2.32s	remaining: 641ms
160:	total: 2.66s	remaining: 314ms
179:	total: 2.97s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.9ms	remaining: 3.56s
20:	total: 348ms	remaining: 2.64s
40:	total: 667ms	remaining: 2.26s
60:	total: 1s	remaining: 1.95s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.63s	remaining: 1.28s
120:	total: 1.97s	remaining: 960ms
140:	total: 2.3s	remaining: 636ms
160:	total: 2.63s	remaining: 311ms
179:	total: 2.94s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.9ms	remaining: 3.56s
20:	total: 330ms	remaining: 2.5s
40:	total: 658ms	remaining: 2.23s
60:	total: 974ms	remaining: 1.9s
80:	total: 1.28s	remaining: 1.57s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.93s	remaining: 939ms
140:	total: 2.26s	remaining: 624ms
160:	total: 2.59s	remaining: 306ms
179:	total: 2.9s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.8ms	remaining: 3.19s
20:	total: 356ms	remaining: 2.69s
40:	total: 678ms	remaining: 2.3s
60:	total: 999ms	remaining: 1.95s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.64s	remaining: 1.28s
120:	total: 1.96s	remaining: 956ms
140:	total: 2.31s	remaining: 639ms
160:	total: 2.64s	remaining: 311ms
179:	total: 2.95s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.6ms	remaining: 3.69s
20:	total: 372ms	remaining: 2.81s
40:	total: 712ms	remaining: 2.41s
60:	total: 1.05s	remaining: 2.05s
80:	total: 1.37s	remaining: 1.68s
100:	total: 1.7s	remaining: 1.33s
120:	total: 2.02s	remaining: 986ms
140:	total: 2.36s	remaining: 652ms
160:	total: 2.71s	remaining: 320ms
179:	total: 3.02s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.9ms	remaining: 3.38s
20:	total: 351ms	remaining: 2.66s
40:	total: 674ms	remaining: 2.29s
60:	total: 1.01s	remaining: 1.96s
80:	total: 1.33s	remaining: 1.63s
100:	total: 1.65s	remaining: 1.29s
120:	total: 1.98s	remaining: 967ms
140:	total: 2.32s	remaining: 643ms
160:	total: 2.65s	remaining: 312ms
179:	total: 2.95s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.5ms	remaining: 3.13s
20:	total: 341ms	remaining: 2.58s
40:	total: 678ms	remaining: 2.3s
60:	total: 1.02s	remaining: 2s
80:	total: 1.36s	remaining: 1.67s
100:	total: 1.72s	remaining: 1.34s
120:	total: 2.06s	remaining: 1s
140:	total: 2.4s	remaining: 665ms
160:	total: 2.76s	remaining: 325ms
179:	total: 3.08s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.9ms	remaining: 3.03s
20:	total: 341ms	remaining: 2.58s
40:	total: 676ms	remaining: 2.29s
60:	total: 1s	remaining: 1.96s
80:	total: 1.33s	remaining: 1.62s
100:	total: 1.65s	remaining: 1.29s
120:	total: 1.98s	remaining: 964ms
140:	total: 2.3s	remaining: 636ms
160:	total: 2.63s	remaining: 311ms
179:	total: 2.94s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.1ms	remaining: 3.24s
20:	total: 338ms	remaining: 2.56s
40:	total: 656ms	remaining: 2.22s
60:	total: 995ms	remaining: 1.94s
80:	total: 1.31s	remaining: 1.61s
100:	total: 1.64s	remaining: 1.28s
120:	total: 1.97s	remaining: 962ms
140:	total: 2.32s	remaining: 641ms
160:	total: 2.68s	remaining: 316ms
179:	total: 3s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.5ms	remaining: 3.49s
20:	total: 343ms	remaining: 2.6s
40:	total: 666ms	remaining: 2.26s
60:	total: 985ms	remaining: 1.92s
80:	total: 1.32s	remaining: 1.61s
100:	total: 1.65s	remaining: 1.29s
120:	total: 1.97s	remaining: 959ms
140:	total: 2.32s	remaining: 642ms
160:	total: 2.65s	remaining: 312ms
179:	total: 2.96s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.1ms	remaining: 3.24s
20:	total: 344ms	remaining: 2.6s
40:	total: 678ms	remaining: 2.3s
60:	total: 996ms	remaining: 1.94s
80:	total: 1.32s	remaining: 1.62s
100:	total: 1.64s	remaining: 1.28s
120:	total: 1.97s	remaining: 958ms
140:	total: 2.29s	remaining: 634ms
160:	total: 2.62s	remaining: 309ms
179:	total: 2.94s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.2ms	remaining: 3.62s
20:	total: 344ms	remaining: 2.61s
40:	total: 667ms	remaining: 2.26s
60:	total: 1s	remaining: 1.95s
80:	total: 1.33s	remaining: 1.63s
100:	total: 1.66s	remaining: 1.3s
120:	total: 1.98s	remaining: 966ms
140:	total: 2.31s	remaining: 639ms
160:	total: 2.63s	remaining: 310ms
179:	total: 2.93s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.6ms	remaining: 2.97s
20:	total: 326ms	remaining: 2.47s
40:	total: 643ms	remaining: 2.18s
60:	total: 956ms	remaining: 1.86s
80:	total: 1.27s	remaining: 1.55s
100:	total: 1.57s	remaining: 1.23s
120:	total: 1.9s	remaining: 926ms
140:	total: 2.22s	remaining: 613ms
160:	total: 2.54s	remaining: 299ms
179:	total: 2.85s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.6ms	remaining: 3.51s
20:	total: 328ms	remaining: 2.48s
40:	total: 648ms	remaining: 2.2s
60:	total: 984ms	remaining: 1.92s
80:	total: 1.33s	remaining: 1.63s
100:	total: 1.67s	remaining: 1.3s
120:	total: 2.01s	remaining: 980ms
140:	total: 2.33s	remaining: 646ms
160:	total: 2.68s	remaining: 316ms
179:	total: 2.98s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.7ms	remaining: 2.99s
20:	total: 354ms	remaining: 2.68s
40:	total: 690ms	remaining: 2.34s
60:	total: 1s	remaining: 1.96s
80:	total: 1.32s	remaining: 1.61s
100:	total: 1.63s	remaining: 1.28s
120:	total: 1.99s	remaining: 969ms
140:	total: 2.36s	remaining: 654ms
160:	total: 2.74s	remaining: 323ms
179:	total: 3.08s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.8ms	remaining: 3.01s
20:	total: 417ms	remaining: 3.16s
40:	total: 779ms	remaining: 2.64s
60:	total: 1.15s	remaining: 2.24s
80:	total: 1.51s	remaining: 1.85s
100:	total: 1.86s	remaining: 1.46s
120:	total: 2.21s	remaining: 1.08s
140:	total: 2.59s	remaining: 716ms
160:	total: 2.93s	remaining: 346ms
179:	total: 3.27s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.9ms	remaining: 3.02s
20:	total: 330ms	remaining: 2.5s
40:	total: 647ms	remaining: 2.19s
60:	total: 970ms	remaining: 1.89s
80:	total: 1.28s	remaining: 1.57s
100:	total: 1.59s	remaining: 1.25s
120:	total: 1.91s	remaining: 933ms
140:	total: 2.24s	remaining: 619ms
160:	total: 2.56s	remaining: 302ms
179:	total: 2.9s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.2ms	remaining: 3.26s
20:	total: 338ms	remaining: 2.56s
40:	total: 656ms	remaining: 2.23s
60:	total: 988ms	remaining: 1.93s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.65s	remaining: 1.29s
120:	total: 1.98s	remaining: 965ms
140:	total: 2.32s	remaining: 641ms
160:	total: 2.65s	remaining: 313ms
179:	total: 2.98s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.7ms	remaining: 3.52s
20:	total: 364ms	remaining: 2.76s
40:	total: 687ms	remaining: 2.33s
60:	total: 1.02s	remaining: 1.99s
80:	total: 1.33s	remaining: 1.63s
100:	total: 1.66s	remaining: 1.3s
120:	total: 1.99s	remaining: 969ms
140:	total: 2.31s	remaining: 638ms
160:	total: 2.63s	remaining: 310ms
179:	total: 2.95s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.9ms	remaining: 3.03s
20:	total: 337ms	remaining: 2.55s
40:	total: 650ms	remaining: 2.21s
60:	total: 965ms	remaining: 1.88s
80:	total: 1.28s	remaining: 1.56s
100:	total: 1.6s	remaining: 1.25s
120:	total: 1.92s	remaining: 934ms
140:	total: 2.23s	remaining: 617ms
160:	total: 2.55s	remaining: 301ms
179:	total: 2.85s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.3ms	remaining: 3.28s
20:	total: 331ms	remaining: 2.51s
40:	total: 685ms	remaining: 2.32s
60:	total: 988ms	remaining: 1.93s
80:	total: 1.33s	remaining: 1.62s
100:	total: 1.67s	remaining: 1.31s
120:	total: 2.01s	remaining: 978ms
140:	total: 2.34s	remaining: 648ms
160:	total: 2.68s	remaining: 316ms
179:	total: 2.98s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 15.8ms	remaining: 2.83s
20:	total: 338ms	remaining: 2.56s
40:	total: 667ms	remaining: 2.26s
60:	total: 990ms	remaining: 1.93s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.62s	remaining: 1.27s
120:	total: 1.95s	remaining: 951ms
140:	total: 2.28s	remaining: 630ms
160:	total: 2.6s	remaining: 306ms
179:	total: 2.91s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.4ms	remaining: 3.3s
20:	total: 347ms	remaining: 2.63s
40:	total: 664ms	remaining: 2.25s
60:	total: 984ms	remaining: 1.92s
80:	total: 1.29s	remaining: 1.58s
100:	total: 1.62s	remaining: 1.26s
120:	total: 1.93s	remaining: 943ms
140:	total: 2.26s	remaining: 626ms
160:	total: 2.62s	remaining: 309ms
179:	total: 2.94s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.4ms	remaining: 3.29s
20:	total: 330ms	remaining: 2.5s
40:	total: 652ms	remaining: 2.21s
60:	total: 965ms	remaining: 1.88s
80:	total: 1.29s	remaining: 1.57s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.94s	remaining: 945ms
140:	total: 2.27s	remaining: 629ms
160:	total: 2.62s	remaining: 309ms
179:	total: 2.93s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.3ms	remaining: 2.92s
20:	total: 329ms	remaining: 2.49s
40:	total: 654ms	remaining: 2.22s
60:	total: 995ms	remaining: 1.94s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.63s	remaining: 1.27s
120:	total: 1.94s	remaining: 947ms
140:	total: 2.26s	remaining: 626ms
160:	total: 2.59s	remaining: 306ms
179:	total: 2.9s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.2ms	remaining: 3.27s
20:	total: 372ms	remaining: 2.82s
40:	total: 719ms	remaining: 2.44s
60:	total: 1.06s	remaining: 2.07s
80:	total: 1.42s	remaining: 1.74s
100:	total: 1.77s	remaining: 1.38s
120:	total: 2.09s	remaining: 1.02s
140:	total: 2.43s	remaining: 673ms
160:	total: 2.77s	remaining: 327ms
179:	total: 3.09s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.2ms	remaining: 3.26s
20:	total: 335ms	remaining: 2.54s
40:	total: 660ms	remaining: 2.24s
60:	total: 990ms	remaining: 1.93s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.62s	remaining: 1.26s
120:	total: 1.94s	remaining: 946ms
140:	total: 2.27s	remaining: 629ms
160:	total: 2.6s	remaining: 307ms
179:	total: 2.92s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.9ms	remaining: 3.03s
20:	total: 346ms	remaining: 2.62s
40:	total: 653ms	remaining: 2.21s
60:	total: 967ms	remaining: 1.89s
80:	total: 1.28s	remaining: 1.57s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.93s	remaining: 943ms
140:	total: 2.29s	remaining: 633ms
160:	total: 2.64s	remaining: 311ms
179:	total: 2.98s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20ms	remaining: 3.59s
20:	total: 345ms	remaining: 2.61s
40:	total: 656ms	remaining: 2.22s
60:	total: 989ms	remaining: 1.93s
80:	total: 1.3s	remaining: 1.59s
100:	total: 1.62s	remaining: 1.27s
120:	total: 1.94s	remaining: 946ms
140:	total: 2.26s	remaining: 626ms
160:	total: 2.61s	remaining: 308ms
179:	total: 2.93s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.2ms	remaining: 3.62s
20:	total: 328ms	remaining: 2.48s
40:	total: 644ms	remaining: 2.18s
60:	total: 962ms	remaining: 1.88s
80:	total: 1.29s	remaining: 1.57s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.93s	remaining: 943ms
140:	total: 2.25s	remaining: 622ms
160:	total: 2.58s	remaining: 305ms
179:	total: 2.89s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.6ms	remaining: 3.51s
20:	total: 365ms	remaining: 2.76s
40:	total: 720ms	remaining: 2.44s
60:	total: 1.06s	remaining: 2.06s
80:	total: 1.38s	remaining: 1.68s
100:	total: 1.7s	remaining: 1.33s
120:	total: 2.02s	remaining: 988ms
140:	total: 2.35s	remaining: 649ms
160:	total: 2.68s	remaining: 316ms
179:	total: 2.98s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.8ms	remaining: 3s
20:	total: 323ms	remaining: 2.45s
40:	total: 640ms	remaining: 2.17s
60:	total: 960ms	remaining: 1.87s
80:	total: 1.27s	remaining: 1.56s
100:	total: 1.58s	remaining: 1.24s
120:	total: 1.9s	remaining: 926ms
140:	total: 2.22s	remaining: 613ms
160:	total: 2.54s	remaining: 299ms
179:	total: 2.87s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.2ms	remaining: 3.25s
20:	total: 357ms	remaining: 2.7s
40:	total: 674ms	remaining: 2.28s
60:	total: 990ms	remaining: 1.93s
80:	total: 1.33s	remaining: 1.62s
100:	total: 1.67s	remaining: 1.3s
120:	total: 2.02s	remaining: 986ms
140:	total: 2.37s	remaining: 655ms
160:	total: 2.71s	remaining: 320ms
179:	total: 3.04s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.1ms	remaining: 3.59s
20:	total: 343ms	remaining: 2.6s
40:	total: 669ms	remaining: 2.27s
60:	total: 991ms	remaining: 1.93s
80:	total: 1.3s	remaining: 1.59s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.93s	remaining: 943ms
140:	total: 2.25s	remaining: 621ms
160:	total: 2.56s	remaining: 303ms
179:	total: 2.87s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18ms	remaining: 3.22s
20:	total: 368ms	remaining: 2.79s
40:	total: 716ms	remaining: 2.43s
60:	total: 1.07s	remaining: 2.08s
80:	total: 1.45s	remaining: 1.77s
100:	total: 1.77s	remaining: 1.39s
120:	total: 2.09s	remaining: 1.02s
140:	total: 2.43s	remaining: 673ms
160:	total: 2.86s	remaining: 337ms
179:	total: 3.24s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 23.6ms	remaining: 4.23s
20:	total: 366ms	remaining: 2.77s
40:	total: 746ms	remaining: 2.53s
60:	total: 1.09s	remaining: 2.12s
80:	total: 1.42s	remaining: 1.73s
100:	total: 1.77s	remaining: 1.38s
120:	total: 2.1s	remaining: 1.03s
140:	total: 2.45s	remaining: 677ms
160:	total: 2.8s	remaining: 330ms
179:	total: 3.11s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.9ms	remaining: 3.37s
20:	total: 337ms	remaining: 2.55s
40:	total: 650ms	remaining: 2.2s
60:	total: 959ms	remaining: 1.87s
80:	total: 1.28s	remaining: 1.56s
100:	total: 1.59s	remaining: 1.24s
120:	total: 1.91s	remaining: 930ms
140:	total: 2.22s	remaining: 614ms
160:	total: 2.54s	remaining: 300ms
179:	total: 2.84s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.3ms	remaining: 3.46s
20:	total: 351ms	remaining: 2.66s
40:	total: 682ms	remaining: 2.31s
60:	total: 1.02s	remaining: 1.99s
80:	total: 1.35s	remaining: 1.65s
100:	total: 1.67s	remaining: 1.3s
120:	total: 2s	remaining: 976ms
140:	total: 2.32s	remaining: 642ms
160:	total: 2.64s	remaining: 312ms
179:	total: 2.96s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.2ms	remaining: 3.08s
20:	total: 325ms	remaining: 2.46s
40:	total: 634ms	remaining: 2.15s
60:	total: 946ms	remaining: 1.84s
80:	total: 1.26s	remaining: 1.54s
100:	total: 1.58s	remaining: 1.24s
120:	total: 1.89s	remaining: 923ms
140:	total: 2.21s	remaining: 613ms
160:	total: 2.53s	remaining: 299ms
179:	total: 2.83s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.7ms	remaining: 3.17s
20:	total: 327ms	remaining: 2.48s
40:	total: 634ms	remaining: 2.15s
60:	total: 955ms	remaining: 1.86s
80:	total: 1.27s	remaining: 1.56s
100:	total: 1.59s	remaining: 1.25s
120:	total: 1.92s	remaining: 938ms
140:	total: 2.25s	remaining: 623ms
160:	total: 2.57s	remaining: 304ms
179:	total: 2.88s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.7ms	remaining: 2.99s
20:	total: 335ms	remaining: 2.53s
40:	total: 658ms	remaining: 2.23s
60:	total: 974ms	remaining: 1.9s
80:	total: 1.29s	remaining: 1.57s
100:	total: 1.62s	remaining: 1.27s
120:	total: 1.94s	remaining: 945ms
140:	total: 2.25s	remaining: 623ms
160:	total: 2.58s	remaining: 304ms
179:	total: 2.89s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.8ms	remaining: 3.19s
20:	total: 342ms	remaining: 2.59s
40:	total: 653ms	remaining: 2.21s
60:	total: 961ms	remaining: 1.88s
80:	total: 1.28s	remaining: 1.56s
100:	total: 1.59s	remaining: 1.24s
120:	total: 1.91s	remaining: 929ms
140:	total: 2.22s	remaining: 614ms
160:	total: 2.54s	remaining: 300ms
179:	total: 2.86s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.7ms	remaining: 3.52s
20:	total: 349ms	remaining: 2.64s
40:	total: 679ms	remaining: 2.3s
60:	total: 997ms	remaining: 1.94s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.92s	remaining: 938ms
140:	total: 2.24s	remaining: 620ms
160:	total: 2.56s	remaining: 302ms
179:	total: 2.86s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.8ms	remaining: 3.37s
20:	total: 332ms	remaining: 2.51s
40:	total: 649ms	remaining: 2.2s
60:	total: 960ms	remaining: 1.87s
80:	total: 1.27s	remaining: 1.55s
100:	total: 1.58s	remaining: 1.23s
120:	total: 1.89s	remaining: 923ms
140:	total: 2.21s	remaining: 613ms
160:	total: 2.54s	remaining: 300ms
179:	total: 2.85s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.7ms	remaining: 3.17s
20:	total: 343ms	remaining: 2.59s
40:	total: 667ms	remaining: 2.26s
60:	total: 983ms	remaining: 1.92s
80:	total: 1.3s	remaining: 1.59s
100:	total: 1.62s	remaining: 1.26s
120:	total: 1.93s	remaining: 943ms
140:	total: 2.26s	remaining: 626ms
160:	total: 2.6s	remaining: 307ms
179:	total: 2.92s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 19.2ms	remaining: 3.44s
20:	total: 348ms	remaining: 2.63s
40:	total: 670ms	remaining: 2.27s
60:	total: 982ms	remaining: 1.91s
80:	total: 1.29s	remaining: 1.57s
100:	total: 1.6s	remaining: 1.25s
120:	total: 1.92s	remaining: 934ms
140:	total: 2.23s	remaining: 618ms
160:	total: 2.55s	remaining: 301ms
179:	total: 2.88s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 22ms	remaining: 3.94s
20:	total: 364ms	remaining: 2.76s
40:	total: 704ms	remaining: 2.39s
60:	total: 1.01s	remaining: 1.98s
80:	total: 1.32s	remaining: 1.62s
100:	total: 1.63s	remaining: 1.28s
120:	total: 1.95s	remaining: 950ms
140:	total: 2.26s	remaining: 626ms
160:	total: 2.6s	remaining: 306ms
179:	total: 2.93s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 20.9ms	remaining: 3.75s
20:	total: 361ms	remaining: 2.73s
40:	total: 692ms	remaining: 2.35s
60:	total: 1.03s	remaining: 2.01s
80:	total: 1.34s	remaining: 1.64s
100:	total: 1.65s	remaining: 1.29s
120:	total: 1.97s	remaining: 959ms
140:	total: 2.29s	remaining: 633ms
160:	total: 2.61s	remaining: 308ms
179:	total: 2.91s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.2ms	remaining: 3.27s
20:	total: 341ms	remaining: 2.58s
40:	total: 684ms	remaining: 2.32s
60:	total: 1.02s	remaining: 2s
80:	total: 1.33s	remaining: 1.63s
100:	total: 1.65s	remaining: 1.29s
120:	total: 1.97s	remaining: 962ms
140:	total: 2.3s	remaining: 637ms
160:	total: 2.65s	remaining: 312ms
179:	total: 2.94s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 16.5ms	remaining: 2.95s
20:	total: 353ms	remaining: 2.67s
40:	total: 693ms	remaining: 2.35s
60:	total: 1.02s	remaining: 2s
80:	total: 1.35s	remaining: 1.65s
100:	total: 1.69s	remaining: 1.32s
120:	total: 2.01s	remaining: 982ms
140:	total: 2.34s	remaining: 648ms
160:	total: 2.67s	remaining: 315ms
179:	total: 2.97s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.7ms	remaining: 3.16s
20:	total: 345ms	remaining: 2.61s
40:	total: 671ms	remaining: 2.27s
60:	total: 996ms	remaining: 1.94s
80:	total: 1.31s	remaining: 1.6s
100:	total: 1.61s	remaining: 1.26s
120:	total: 1.93s	remaining: 942ms
140:	total: 2.24s	remaining: 621ms
160:	total: 2.56s	remaining: 303ms
179:	total: 2.87s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.3ms	remaining: 3.09s
20:	total: 337ms	remaining: 2.55s
40:	total: 654ms	remaining: 2.21s
60:	total: 963ms	remaining: 1.88s
80:	total: 1.27s	remaining: 1.56s
100:	total: 1.6s	remaining: 1.25s
120:	total: 1.94s	remaining: 945ms
140:	total: 2.25s	remaining: 623ms
160:	total: 2.58s	remaining: 304ms
179:	total: 2.89s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 15.1ms	remaining: 2.7s
20:	total: 324ms	remaining: 2.45s
40:	total: 635ms	remaining: 2.15s
60:	total: 960ms	remaining: 1.87s
80:	total: 1.27s	remaining: 1.55s
100:	total: 1.57s	remaining: 1.23s
120:	total: 1.89s	remaining: 920ms
140:	total: 2.2s	remaining: 610ms
160:	total: 2.52s	remaining: 297ms
179:	total: 2.82s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.5ms	remaining: 3.31s
20:	total: 342ms	remaining: 2.59s
40:	total: 651ms	remaining: 2.21s
60:	total: 959ms	remaining: 1.87s
80:	total: 1.26s	remaining: 1.54s
100:	total: 1.57s	remaining: 1.23s
120:	total: 1.88s	remaining: 918ms
140:	total: 2.2s	remaining: 609ms
160:	total: 2.52s	remaining: 298ms
179:	total: 2.84s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.8ms	remaining: 3.19s
20:	total: 342ms	remaining: 2.59s
40:	total: 680ms	remaining: 2.31s
60:	total: 1s	remaining: 1.96s
80:	total: 1.32s	remaining: 1.62s
100:	total: 1.66s	remaining: 1.3s
120:	total: 2.07s	remaining: 1.01s
140:	total: 2.42s	remaining: 671ms
160:	total: 2.74s	remaining: 324ms
179:	total: 3.05s	remaining: 0us


Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 18.5ms	remaining: 3.31s
20:	total: 333ms	remaining: 2.52s
40:	total: 648ms	remaining: 2.2s
60:	total: 1.03s	remaining: 2.02s
80:	total: 1.41s	remaining: 1.72s
100:	total: 1.76s	remaining: 1.38s
120:	total: 2.14s	remaining: 1.04s
140:	total: 2.5s	remaining: 692ms
160:	total: 2.86s	remaining: 337ms
179:	total: 3.19s	remaining: 0us


,estimator,<catboost.cor...00194EDF55C00>
,param_grid,"{'depth': [2], 'l2_leaf_reg': [40, 50, ...], 'learning_rate': [0.03, 0.04, ...]}"
,scoring,'roc_auc'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,True


In [53]:
results = pd.DataFrame(gs1.cv_results_)
results["gap"] = results["mean_train_score"] - results["mean_test_score"]
params_df = results["params"].apply(pd.Series)

final_df = pd.concat([
    params_df,
    results[["mean_train_score","mean_test_score","gap"]]
], axis=1)

final_df.sort_values(
    ["mean_test_score","gap"],
    ascending=[False,True]
).head(10)

,depth,l2_leaf_reg,learning_rate,mean_train_score,mean_test_score,gap
4,2.0,50.0,0.04,0.907350,0.812653,0.094698
1,2.0,40.0,0.04,0.907861,0.812040,0.095821
8,2.0,60.0,0.05,0.917999,0.810544,0.107455
7,2.0,60.0,0.04,0.905983,0.810516,0.095466
10,2.0,70.0,0.04,0.905415,0.810459,0.094956
11,2.0,70.0,0.05,0.917146,0.810219,0.106928
2,2.0,40.0,0.05,0.920599,0.809685,0.110914
5,2.0,50.0,0.05,0.919334,0.809661,0.109672
9,2.0,70.0,0.03,0.891021,0.807914,0.083107
3,2.0,50.0,0.03,0.893049,0.806951,0.086098


| Metric    | Trước tuning | Sau tuning | Ý nghĩa |
|-----------|--------------|------------|---------|
| Train AUC | 0.9979 | 0.9073 | Giảm overfitting |
| Test AUC  | 0.7890 | 0.8127 | Khả năng dự đoán tốt hơn |
| Gap       | 0.2089 | 0.0947 | Generalization tốt hơn |

Sau quá trình hyperparameter tuning và cross-validation với CatBoost, hiệu năng mô hình đã được cải thiện:

- Test AUC tăng từ 0.7890 lên 0.8127 (+0.0237), cho thấy khả năng dự đoán trên dữ liệu chưa thấy được cải thiện.

- Train AUC giảm từ 0.9979 xuống 0.9073, cho thấy mô hình đã giảm hiện tượng overfitting.

- Khoảng cách Train–Test (Gap) giảm từ 0.2089 xuống 0.0947, chứng tỏ khả năng tổng quát hóa của mô hình tốt hơn.

Cấu hình hyperparameter tốt nhất được tìm thấy:
- `depth = 4`
- `learning_rate = 0.04`
- `l2_leaf_reg = 50`  
=> Với cấu hình này, mô hình đạt Test AUC ≈ 0.81, cùng với Train–Test gap < 0.1, cho thấy mức độ overfitting đã được kiểm soát và mô hình có khả năng dự đoán ổn định hơn trên dữ liệu kiểm thử.

#### Train lại model với best params + full train data

In [61]:
best_model = CatBoostClassifier(
    depth=2,
    learning_rate=0.04,
    l2_leaf_reg=50,
    auto_class_weights='Balanced',
    iterations=best_iter,
    eval_metric="AUC",
    task_type='GPU',
    verbose=50
)

best_model.fit(train_pool)

Default metric period is 5 because AUC is/are not implemented for GPU


0:	total: 17.3ms	remaining: 2.58s
50:	total: 936ms	remaining: 1.82s
100:	total: 1.87s	remaining: 907ms
149:	total: 2.8s	remaining: 0us


## PHASE 5 – Đánh giá sau khi train lại model với full data

In [62]:
# Train
train_pred = best_model.predict_proba(train_pool)[:,1]
train_auc = roc_auc_score(y_train, train_pred)

# Test
test_pred = best_model.predict_proba(test_pool)[:,1]
test_auc = roc_auc_score(y_test, test_pred)

print("Train AUC:", train_auc)
print("Test AUC:", test_auc)
print("Gap:", train_auc - test_auc)

Train AUC: 0.8901462581402797
Test AUC: 0.8008441726246878
Gap: 0.08930208551559193


In [63]:
from sklearn.metrics import classification_report

y_pred = best_model.predict(test_pool)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.79      0.86       247
           1       0.41      0.74      0.53        47

    accuracy                           0.79       294
   macro avg       0.67      0.77      0.69       294
weighted avg       0.86      0.79      0.81       294



### Đánh giá mô hình (CatBoost)

Sau khi thực hiện tuning tham số cho mô hình CatBoost, hiệu năng mô hình đã được cải thiện rõ rệt.

| Metric | Trước tuning | Sau tuning |
|------|------|------|
| Train AUC | 0.9979 | 0.89014 |
| Test AUC | 0.7890 | 0.80084 |
| Gap | 0.2089 | 0.089 |

#### Nhận xét

- **Overfitting giảm đáng kể**: Ban đầu mô hình có Train AUC gần 1 (0.9979) nhưng Test AUC thấp hơn nhiều, dẫn đến gap lớn (~0.21), cho thấy mô hình bị overfitting.
- **Khả năng tổng quát hóa được cải thiện**: Sau khi tuning, gap giảm xuống còn ~0.09, cho thấy mô hình tổng quát hóa tốt hơn trên dữ liệu chưa thấy.
- **Hiệu năng trên test set tăng**: Test AUC tăng từ **0.789 → 0.80084**, cho thấy các tham số mới giúp mô hình học được các pattern tốt hơn.
- **Train AUC giảm là hợp lý**: Train AUC giảm xuống 0.896 cho thấy mô hình không còn ghi nhớ dữ liệu train mà học các đặc trưng tổng quát hơn.

#### Kết luận

Việc tuning tham số đã giúp **giảm overfitting và cải thiện hiệu năng dự đoán của mô hình**, đạt được sự cân bằng tốt giữa khả năng học dữ liệu huấn luyện và khả năng tổng quát hóa.

## PHASE 6 – Giải thích model

In [64]:
importances = best_model.get_feature_importance()
features = X.columns

pd.Series(importances, index=features)\
  .sort_values(ascending=False)\
  .head(10)

OverTime                   16.468882
JobRole                    11.311574
StockOptionLevel            9.494780
YearsWithCurrManager        7.292331
Age                         7.154171
MonthlyIncome               5.630224
NumCompaniesWorked          5.624582
EnvironmentSatisfaction     4.893169
YearsAtCompany              4.668608
TotalWorkingYears           4.594638
dtype: float64

### Phân tích

- Kết quả feature importance từ CatBoost cho thấy các yếu tố liên quan đến điều kiện làm việc, thu nhập và kinh nghiệm nghề nghiệp có ảnh hưởng lớn đến dự đoán của mô hình.

- OverTime (16.47%) là yếu tố quan trọng nhất. Điều này cho thấy việc làm thêm giờ có ảnh hưởng mạnh đến khả năng xảy ra kết quả mục tiêu (ví dụ: nghỉ việc).

- JobRole (11.31%) đứng thứ hai, cho thấy vai trò công việc khác nhau có mức độ rủi ro khác nhau.

- StockOptionLevel (9.49%) cũng có ảnh hưởng đáng kể, cho thấy các chính sách cổ phiếu thưởng có thể tác động đến hành vi nhân viên.

- Các yếu tố liên quan đến kinh nghiệm và thời gian làm việc như YearsWithCurrManager, YearsAtCompany, và TotalWorkingYears cũng đóng vai trò quan trọng trong dự đoán của mô hình.

- Ngoài ra, các yếu tố cá nhân như Age và MonthlyIncome cũng góp phần đáng kể trong việc phân biệt các trường hợp.

- Nhìn chung, mô hình không chỉ dựa vào một biến duy nhất mà khai thác nhiều khía cạnh khác nhau của hồ sơ nhân viên, bao gồm điều kiện làm việc, kinh nghiệm và chế độ đãi ngộ.